// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="upconv_core_top_ucb0_upconv_core_top_ucb0,hls_ip_2024_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu7ev-ffvc1156-2-e,HLS_INPUT_CLOCK=3.333000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.433090,HLS_SYN_LAT=17523951,HLS_SYN_TPT=none,HLS_SYN_MEM=204,HLS_SYN_DSP=0,HLS_SYN_FF=73903,HLS_SYN_LUT=52582,HLS_VERSION=2024_2}" *)

module upconv_core_top_ucb0 (
        ap_clk,
        ap_rst_n,
        m_axi_gmem_in_AWVALID,
        m_axi_gmem_in_AWREADY,
        m_axi_gmem_in_AWADDR,
        m_axi_gmem_in_AWID,
        m_axi_gmem_in_AWLEN,
        m_axi_gmem_in_AWSIZE,
        m_axi_gmem_in_AWBURST,
        m_axi_gmem_in_AWLOCK,
        m_axi_gmem_in_AWCACHE,
        m_axi_gmem_in_AWPROT,
        m_axi_gmem_in_AWQOS,
        m_axi_gmem_in_AWREGION,
        m_axi_gmem_in_AWUSER,
        m_axi_gmem_in_WVALID,
        m_axi_gmem_in_WREADY,
        m_axi_gmem_in_WDATA,
        m_axi_gmem_in_WSTRB,
        m_axi_gmem_in_WLAST,
        m_axi_gmem_in_WID,
        m_axi_gmem_in_WUSER,
        m_axi_gmem_in_ARVALID,
        m_axi_gmem_in_ARREADY,
        m_axi_gmem_in_ARADDR,
        m_axi_gmem_in_ARID,
        m_axi_gmem_in_ARLEN,
        m_axi_gmem_in_ARSIZE,
        m_axi_gmem_in_ARBURST,
        m_axi_gmem_in_ARLOCK,
        m_axi_gmem_in_ARCACHE,
        m_axi_gmem_in_ARPROT,
        m_axi_gmem_in_ARQOS,
        m_axi_gmem_in_ARREGION,
        m_axi_gmem_in_ARUSER,
        m_axi_gmem_in_RVALID,
        m_axi_gmem_in_RREADY,
        m_axi_gmem_in_RDATA,
        m_axi_gmem_in_RLAST,
        m_axi_gmem_in_RID,
        m_axi_gmem_in_RUSER,
        m_axi_gmem_in_RRESP,
        m_axi_gmem_in_BVALID,
        m_axi_gmem_in_BREADY,
        m_axi_gmem_in_BRESP,
        m_axi_gmem_in_BID,
        m_axi_gmem_in_BUSER,
        m_axi_gmem_weight_AWVALID,
        m_axi_gmem_weight_AWREADY,
        m_axi_gmem_weight_AWADDR,
        m_axi_gmem_weight_AWID,
        m_axi_gmem_weight_AWLEN,
        m_axi_gmem_weight_AWSIZE,
        m_axi_gmem_weight_AWBURST,
        m_axi_gmem_weight_AWLOCK,
        m_axi_gmem_weight_AWCACHE,
        m_axi_gmem_weight_AWPROT,
        m_axi_gmem_weight_AWQOS,
        m_axi_gmem_weight_AWREGION,
        m_axi_gmem_weight_AWUSER,
        m_axi_gmem_weight_WVALID,
        m_axi_gmem_weight_WREADY,
        m_axi_gmem_weight_WDATA,
        m_axi_gmem_weight_WSTRB,
        m_axi_gmem_weight_WLAST,
        m_axi_gmem_weight_WID,
        m_axi_gmem_weight_WUSER,
        m_axi_gmem_weight_ARVALID,
        m_axi_gmem_weight_ARREADY,
        m_axi_gmem_weight_ARADDR,
        m_axi_gmem_weight_ARID,
        m_axi_gmem_weight_ARLEN,
        m_axi_gmem_weight_ARSIZE,
        m_axi_gmem_weight_ARBURST,
        m_axi_gmem_weight_ARLOCK,
        m_axi_gmem_weight_ARCACHE,
        m_axi_gmem_weight_ARPROT,
        m_axi_gmem_weight_ARQOS,
        m_axi_gmem_weight_ARREGION,
        m_axi_gmem_weight_ARUSER,
        m_axi_gmem_weight_RVALID,
        m_axi_gmem_weight_RREADY,
        m_axi_gmem_weight_RDATA,
        m_axi_gmem_weight_RLAST,
        m_axi_gmem_weight_RID,
        m_axi_gmem_weight_RUSER,
        m_axi_gmem_weight_RRESP,
        m_axi_gmem_weight_BVALID,
        m_axi_gmem_weight_BREADY,
        m_axi_gmem_weight_BRESP,
        m_axi_gmem_weight_BID,
        m_axi_gmem_weight_BUSER,
        m_axi_gmem_param_AWVALID,
        m_axi_gmem_param_AWREADY,
        m_axi_gmem_param_AWADDR,
        m_axi_gmem_param_AWID,
        m_axi_gmem_param_AWLEN,
        m_axi_gmem_param_AWSIZE,
        m_axi_gmem_param_AWBURST,
        m_axi_gmem_param_AWLOCK,
        m_axi_gmem_param_AWCACHE,
        m_axi_gmem_param_AWPROT,
        m_axi_gmem_param_AWQOS,
        m_axi_gmem_param_AWREGION,
        m_axi_gmem_param_AWUSER,
        m_axi_gmem_param_WVALID,
        m_axi_gmem_param_WREADY,
        m_axi_gmem_param_WDATA,
        m_axi_gmem_param_WSTRB,
        m_axi_gmem_param_WLAST,
        m_axi_gmem_param_WID,
        m_axi_gmem_param_WUSER,
        m_axi_gmem_param_ARVALID,
        m_axi_gmem_param_ARREADY,
        m_axi_gmem_param_ARADDR,
        m_axi_gmem_param_ARID,
        m_axi_gmem_param_ARLEN,
        m_axi_gmem_param_ARSIZE,
        m_axi_gmem_param_ARBURST,
        m_axi_gmem_param_ARLOCK,
        m_axi_gmem_param_ARCACHE,
        m_axi_gmem_param_ARPROT,
        m_axi_gmem_param_ARQOS,
        m_axi_gmem_param_ARREGION,
        m_axi_gmem_param_ARUSER,
        m_axi_gmem_param_RVALID,
        m_axi_gmem_param_RREADY,
        m_axi_gmem_param_RDATA,
        m_axi_gmem_param_RLAST,
        m_axi_gmem_param_RID,
        m_axi_gmem_param_RUSER,
        m_axi_gmem_param_RRESP,
        m_axi_gmem_param_BVALID,
        m_axi_gmem_param_BREADY,
        m_axi_gmem_param_BRESP,
        m_axi_gmem_param_BID,
        m_axi_gmem_param_BUSER,
        m_axi_gmem_out_AWVALID,
        m_axi_gmem_out_AWREADY,
        m_axi_gmem_out_AWADDR,
        m_axi_gmem_out_AWID,
        m_axi_gmem_out_AWLEN,
        m_axi_gmem_out_AWSIZE,
        m_axi_gmem_out_AWBURST,
        m_axi_gmem_out_AWLOCK,
        m_axi_gmem_out_AWCACHE,
        m_axi_gmem_out_AWPROT,
        m_axi_gmem_out_AWQOS,
        m_axi_gmem_out_AWREGION,
        m_axi_gmem_out_AWUSER,
        m_axi_gmem_out_WVALID,
        m_axi_gmem_out_WREADY,
        m_axi_gmem_out_WDATA,
        m_axi_gmem_out_WSTRB,
        m_axi_gmem_out_WLAST,
        m_axi_gmem_out_WID,
        m_axi_gmem_out_WUSER,
        m_axi_gmem_out_ARVALID,
        m_axi_gmem_out_ARREADY,
        m_axi_gmem_out_ARADDR,
        m_axi_gmem_out_ARID,
        m_axi_gmem_out_ARLEN,
        m_axi_gmem_out_ARSIZE,
        m_axi_gmem_out_ARBURST,
        m_axi_gmem_out_ARLOCK,
        m_axi_gmem_out_ARCACHE,
        m_axi_gmem_out_ARPROT,
        m_axi_gmem_out_ARQOS,
        m_axi_gmem_out_ARREGION,
        m_axi_gmem_out_ARUSER,
        m_axi_gmem_out_RVALID,
        m_axi_gmem_out_RREADY,
        m_axi_gmem_out_RDATA,
        m_axi_gmem_out_RLAST,
        m_axi_gmem_out_RID,
        m_axi_gmem_out_RUSER,
        m_axi_gmem_out_RRESP,
        m_axi_gmem_out_BVALID,
        m_axi_gmem_out_BREADY,
        m_axi_gmem_out_BRESP,
        m_axi_gmem_out_BID,
        m_axi_gmem_out_BUSER,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 21'd1;
parameter    ap_ST_fsm_state2 = 21'd2;
parameter    ap_ST_fsm_state3 = 21'd4;
parameter    ap_ST_fsm_state4 = 21'd8;
parameter    ap_ST_fsm_state5 = 21'd16;
parameter    ap_ST_fsm_state6 = 21'd32;
parameter    ap_ST_fsm_state7 = 21'd64;
parameter    ap_ST_fsm_state8 = 21'd128;
parameter    ap_ST_fsm_state9 = 21'd256;
parameter    ap_ST_fsm_state10 = 21'd512;
parameter    ap_ST_fsm_state11 = 21'd1024;
parameter    ap_ST_fsm_state12 = 21'd2048;
parameter    ap_ST_fsm_state13 = 21'd4096;
parameter    ap_ST_fsm_state14 = 21'd8192;
parameter    ap_ST_fsm_state15 = 21'd16384;
parameter    ap_ST_fsm_state16 = 21'd32768;
parameter    ap_ST_fsm_state17 = 21'd65536;
parameter    ap_ST_fsm_state18 = 21'd131072;
parameter    ap_ST_fsm_state19 = 21'd262144;
parameter    ap_ST_fsm_state20 = 21'd524288;
parameter    ap_ST_fsm_state21 = 21'd1048576;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 7;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_IN_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM_IN_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM_IN_DATA_WIDTH = 256;
parameter    C_M_AXI_GMEM_IN_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_IN_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_IN_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_IN_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_IN_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_IN_USER_VALUE = 0;
parameter    C_M_AXI_GMEM_IN_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM_IN_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_OUT_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM_OUT_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM_OUT_DATA_WIDTH = 256;
parameter    C_M_AXI_GMEM_OUT_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_OUT_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_OUT_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_OUT_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_OUT_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_OUT_USER_VALUE = 0;
parameter    C_M_AXI_GMEM_OUT_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM_OUT_CACHE_VALUE = 3;
parameter    C_M_AXI_GMEM_PARAM_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM_PARAM_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM_PARAM_DATA_WIDTH = 256;
parameter    C_M_AXI_GMEM_PARAM_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_PARAM_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_PARAM_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_PARAM_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_PARAM_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_PARAM_USER_VALUE = 0;
parameter    C_M_AXI_GMEM_PARAM_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM_PARAM_CACHE_VALUE = 3;
parameter    C_M_AXI_GMEM_WEIGHT_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM_WEIGHT_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM_WEIGHT_DATA_WIDTH = 256;
parameter    C_M_AXI_GMEM_WEIGHT_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_WEIGHT_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_WEIGHT_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_WEIGHT_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_WEIGHT_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_WEIGHT_USER_VALUE = 0;
parameter    C_M_AXI_GMEM_WEIGHT_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM_WEIGHT_CACHE_VALUE = 3;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM_IN_WSTRB_WIDTH = (256 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM_OUT_WSTRB_WIDTH = (256 / 8);
parameter C_M_AXI_GMEM_PARAM_WSTRB_WIDTH = (256 / 8);
parameter C_M_AXI_GMEM_WEIGHT_WSTRB_WIDTH = (256 / 8);

input   ap_clk;
input   ap_rst_n;
output   m_axi_gmem_in_AWVALID;
input   m_axi_gmem_in_AWREADY;
output  [C_M_AXI_GMEM_IN_ADDR_WIDTH - 1:0] m_axi_gmem_in_AWADDR;
output  [C_M_AXI_GMEM_IN_ID_WIDTH - 1:0] m_axi_gmem_in_AWID;
output  [7:0] m_axi_gmem_in_AWLEN;
output  [2:0] m_axi_gmem_in_AWSIZE;
output  [1:0] m_axi_gmem_in_AWBURST;
output  [1:0] m_axi_gmem_in_AWLOCK;
output  [3:0] m_axi_gmem_in_AWCACHE;
output  [2:0] m_axi_gmem_in_AWPROT;
output  [3:0] m_axi_gmem_in_AWQOS;
output  [3:0] m_axi_gmem_in_AWREGION;
output  [C_M_AXI_GMEM_IN_AWUSER_WIDTH - 1:0] m_axi_gmem_in_AWUSER;
output   m_axi_gmem_in_WVALID;
input   m_axi_gmem_in_WREADY;
output  [C_M_AXI_GMEM_IN_DATA_WIDTH - 1:0] m_axi_gmem_in_WDATA;
output  [C_M_AXI_GMEM_IN_WSTRB_WIDTH - 1:0] m_axi_gmem_in_WSTRB;
output   m_axi_gmem_in_WLAST;
output  [C_M_AXI_GMEM_IN_ID_WIDTH - 1:0] m_axi_gmem_in_WID;
output  [C_M_AXI_GMEM_IN_WUSER_WIDTH - 1:0] m_axi_gmem_in_WUSER;
output   m_axi_gmem_in_ARVALID;
input   m_axi_gmem_in_ARREADY;
output  [C_M_AXI_GMEM_IN_ADDR_WIDTH - 1:0] m_axi_gmem_in_ARADDR;
output  [C_M_AXI_GMEM_IN_ID_WIDTH - 1:0] m_axi_gmem_in_ARID;
output  [7:0] m_axi_gmem_in_ARLEN;
output  [2:0] m_axi_gmem_in_ARSIZE;
output  [1:0] m_axi_gmem_in_ARBURST;
output  [1:0] m_axi_gmem_in_ARLOCK;
output  [3:0] m_axi_gmem_in_ARCACHE;
output  [2:0] m_axi_gmem_in_ARPROT;
output  [3:0] m_axi_gmem_in_ARQOS;
output  [3:0] m_axi_gmem_in_ARREGION;
output  [C_M_AXI_GMEM_IN_ARUSER_WIDTH - 1:0] m_axi_gmem_in_ARUSER;
input   m_axi_gmem_in_RVALID;
output   m_axi_gmem_in_RREADY;
input  [C_M_AXI_GMEM_IN_DATA_WIDTH - 1:0] m_axi_gmem_in_RDATA;
input   m_axi_gmem_in_RLAST;
input  [C_M_AXI_GMEM_IN_ID_WIDTH - 1:0] m_axi_gmem_in_RID;
input  [C_M_AXI_GMEM_IN_RUSER_WIDTH - 1:0] m_axi_gmem_in_RUSER;
input  [1:0] m_axi_gmem_in_RRESP;
input   m_axi_gmem_in_BVALID;
output   m_axi_gmem_in_BREADY;
input  [1:0] m_axi_gmem_in_BRESP;
input  [C_M_AXI_GMEM_IN_ID_WIDTH - 1:0] m_axi_gmem_in_BID;
input  [C_M_AXI_GMEM_IN_BUSER_WIDTH - 1:0] m_axi_gmem_in_BUSER;
output   m_axi_gmem_weight_AWVALID;
input   m_axi_gmem_weight_AWREADY;
output  [C_M_AXI_GMEM_WEIGHT_ADDR_WIDTH - 1:0] m_axi_gmem_weight_AWADDR;
output  [C_M_AXI_GMEM_WEIGHT_ID_WIDTH - 1:0] m_axi_gmem_weight_AWID;
output  [7:0] m_axi_gmem_weight_AWLEN;
output  [2:0] m_axi_gmem_weight_AWSIZE;
output  [1:0] m_axi_gmem_weight_AWBURST;
output  [1:0] m_axi_gmem_weight_AWLOCK;
output  [3:0] m_axi_gmem_weight_AWCACHE;
output  [2:0] m_axi_gmem_weight_AWPROT;
output  [3:0] m_axi_gmem_weight_AWQOS;
output  [3:0] m_axi_gmem_weight_AWREGION;
output  [C_M_AXI_GMEM_WEIGHT_AWUSER_WIDTH - 1:0] m_axi_gmem_weight_AWUSER;
output   m_axi_gmem_weight_WVALID;
input   m_axi_gmem_weight_WREADY;
output  [C_M_AXI_GMEM_WEIGHT_DATA_WIDTH - 1:0] m_axi_gmem_weight_WDATA;
output  [C_M_AXI_GMEM_WEIGHT_WSTRB_WIDTH - 1:0] m_axi_gmem_weight_WSTRB;
output   m_axi_gmem_weight_WLAST;
output  [C_M_AXI_GMEM_WEIGHT_ID_WIDTH - 1:0] m_axi_gmem_weight_WID;
output  [C_M_AXI_GMEM_WEIGHT_WUSER_WIDTH - 1:0] m_axi_gmem_weight_WUSER;
output   m_axi_gmem_weight_ARVALID;
input   m_axi_gmem_weight_ARREADY;
output  [C_M_AXI_GMEM_WEIGHT_ADDR_WIDTH - 1:0] m_axi_gmem_weight_ARADDR;
output  [C_M_AXI_GMEM_WEIGHT_ID_WIDTH - 1:0] m_axi_gmem_weight_ARID;
output  [7:0] m_axi_gmem_weight_ARLEN;
output  [2:0] m_axi_gmem_weight_ARSIZE;
output  [1:0] m_axi_gmem_weight_ARBURST;
output  [1:0] m_axi_gmem_weight_ARLOCK;
output  [3:0] m_axi_gmem_weight_ARCACHE;
output  [2:0] m_axi_gmem_weight_ARPROT;
output  [3:0] m_axi_gmem_weight_ARQOS;
output  [3:0] m_axi_gmem_weight_ARREGION;
output  [C_M_AXI_GMEM_WEIGHT_ARUSER_WIDTH - 1:0] m_axi_gmem_weight_ARUSER;
input   m_axi_gmem_weight_RVALID;
output   m_axi_gmem_weight_RREADY;
input  [C_M_AXI_GMEM_WEIGHT_DATA_WIDTH - 1:0] m_axi_gmem_weight_RDATA;
input   m_axi_gmem_weight_RLAST;
input  [C_M_AXI_GMEM_WEIGHT_ID_WIDTH - 1:0] m_axi_gmem_weight_RID;
input  [C_M_AXI_GMEM_WEIGHT_RUSER_WIDTH - 1:0] m_axi_gmem_weight_RUSER;
input  [1:0] m_axi_gmem_weight_RRESP;
input   m_axi_gmem_weight_BVALID;
output   m_axi_gmem_weight_BREADY;
input  [1:0] m_axi_gmem_weight_BRESP;
input  [C_M_AXI_GMEM_WEIGHT_ID_WIDTH - 1:0] m_axi_gmem_weight_BID;
input  [C_M_AXI_GMEM_WEIGHT_BUSER_WIDTH - 1:0] m_axi_gmem_weight_BUSER;
output   m_axi_gmem_param_AWVALID;
input   m_axi_gmem_param_AWREADY;
output  [C_M_AXI_GMEM_PARAM_ADDR_WIDTH - 1:0] m_axi_gmem_param_AWADDR;
output  [C_M_AXI_GMEM_PARAM_ID_WIDTH - 1:0] m_axi_gmem_param_AWID;
output  [7:0] m_axi_gmem_param_AWLEN;
output  [2:0] m_axi_gmem_param_AWSIZE;
output  [1:0] m_axi_gmem_param_AWBURST;
output  [1:0] m_axi_gmem_param_AWLOCK;
output  [3:0] m_axi_gmem_param_AWCACHE;
output  [2:0] m_axi_gmem_param_AWPROT;
output  [3:0] m_axi_gmem_param_AWQOS;
output  [3:0] m_axi_gmem_param_AWREGION;
output  [C_M_AXI_GMEM_PARAM_AWUSER_WIDTH - 1:0] m_axi_gmem_param_AWUSER;
output   m_axi_gmem_param_WVALID;
input   m_axi_gmem_param_WREADY;
output  [C_M_AXI_GMEM_PARAM_DATA_WIDTH - 1:0] m_axi_gmem_param_WDATA;
output  [C_M_AXI_GMEM_PARAM_WSTRB_WIDTH - 1:0] m_axi_gmem_param_WSTRB;
output   m_axi_gmem_param_WLAST;
output  [C_M_AXI_GMEM_PARAM_ID_WIDTH - 1:0] m_axi_gmem_param_WID;
output  [C_M_AXI_GMEM_PARAM_WUSER_WIDTH - 1:0] m_axi_gmem_param_WUSER;
output   m_axi_gmem_param_ARVALID;
input   m_axi_gmem_param_ARREADY;
output  [C_M_AXI_GMEM_PARAM_ADDR_WIDTH - 1:0] m_axi_gmem_param_ARADDR;
output  [C_M_AXI_GMEM_PARAM_ID_WIDTH - 1:0] m_axi_gmem_param_ARID;
output  [7:0] m_axi_gmem_param_ARLEN;
output  [2:0] m_axi_gmem_param_ARSIZE;
output  [1:0] m_axi_gmem_param_ARBURST;
output  [1:0] m_axi_gmem_param_ARLOCK;
output  [3:0] m_axi_gmem_param_ARCACHE;
output  [2:0] m_axi_gmem_param_ARPROT;
output  [3:0] m_axi_gmem_param_ARQOS;
output  [3:0] m_axi_gmem_param_ARREGION;
output  [C_M_AXI_GMEM_PARAM_ARUSER_WIDTH - 1:0] m_axi_gmem_param_ARUSER;
input   m_axi_gmem_param_RVALID;
output   m_axi_gmem_param_RREADY;
input  [C_M_AXI_GMEM_PARAM_DATA_WIDTH - 1:0] m_axi_gmem_param_RDATA;
input   m_axi_gmem_param_RLAST;
input  [C_M_AXI_GMEM_PARAM_ID_WIDTH - 1:0] m_axi_gmem_param_RID;
input  [C_M_AXI_GMEM_PARAM_RUSER_WIDTH - 1:0] m_axi_gmem_param_RUSER;
input  [1:0] m_axi_gmem_param_RRESP;
input   m_axi_gmem_param_BVALID;
output   m_axi_gmem_param_BREADY;
input  [1:0] m_axi_gmem_param_BRESP;
input  [C_M_AXI_GMEM_PARAM_ID_WIDTH - 1:0] m_axi_gmem_param_BID;
input  [C_M_AXI_GMEM_PARAM_BUSER_WIDTH - 1:0] m_axi_gmem_param_BUSER;
output   m_axi_gmem_out_AWVALID;
input   m_axi_gmem_out_AWREADY;
output  [C_M_AXI_GMEM_OUT_ADDR_WIDTH - 1:0] m_axi_gmem_out_AWADDR;
output  [C_M_AXI_GMEM_OUT_ID_WIDTH - 1:0] m_axi_gmem_out_AWID;
output  [7:0] m_axi_gmem_out_AWLEN;
output  [2:0] m_axi_gmem_out_AWSIZE;
output  [1:0] m_axi_gmem_out_AWBURST;
output  [1:0] m_axi_gmem_out_AWLOCK;
output  [3:0] m_axi_gmem_out_AWCACHE;
output  [2:0] m_axi_gmem_out_AWPROT;
output  [3:0] m_axi_gmem_out_AWQOS;
output  [3:0] m_axi_gmem_out_AWREGION;
output  [C_M_AXI_GMEM_OUT_AWUSER_WIDTH - 1:0] m_axi_gmem_out_AWUSER;
output   m_axi_gmem_out_WVALID;
input   m_axi_gmem_out_WREADY;
output  [C_M_AXI_GMEM_OUT_DATA_WIDTH - 1:0] m_axi_gmem_out_WDATA;
output  [C_M_AXI_GMEM_OUT_WSTRB_WIDTH - 1:0] m_axi_gmem_out_WSTRB;
output   m_axi_gmem_out_WLAST;
output  [C_M_AXI_GMEM_OUT_ID_WIDTH - 1:0] m_axi_gmem_out_WID;
output  [C_M_AXI_GMEM_OUT_WUSER_WIDTH - 1:0] m_axi_gmem_out_WUSER;
output   m_axi_gmem_out_ARVALID;
input   m_axi_gmem_out_ARREADY;
output  [C_M_AXI_GMEM_OUT_ADDR_WIDTH - 1:0] m_axi_gmem_out_ARADDR;
output  [C_M_AXI_GMEM_OUT_ID_WIDTH - 1:0] m_axi_gmem_out_ARID;
output  [7:0] m_axi_gmem_out_ARLEN;
output  [2:0] m_axi_gmem_out_ARSIZE;
output  [1:0] m_axi_gmem_out_ARBURST;
output  [1:0] m_axi_gmem_out_ARLOCK;
output  [3:0] m_axi_gmem_out_ARCACHE;
output  [2:0] m_axi_gmem_out_ARPROT;
output  [3:0] m_axi_gmem_out_ARQOS;
output  [3:0] m_axi_gmem_out_ARREGION;
output  [C_M_AXI_GMEM_OUT_ARUSER_WIDTH - 1:0] m_axi_gmem_out_ARUSER;
input   m_axi_gmem_out_RVALID;
output   m_axi_gmem_out_RREADY;
input  [C_M_AXI_GMEM_OUT_DATA_WIDTH - 1:0] m_axi_gmem_out_RDATA;
input   m_axi_gmem_out_RLAST;
input  [C_M_AXI_GMEM_OUT_ID_WIDTH - 1:0] m_axi_gmem_out_RID;
input  [C_M_AXI_GMEM_OUT_RUSER_WIDTH - 1:0] m_axi_gmem_out_RUSER;
input  [1:0] m_axi_gmem_out_RRESP;
input   m_axi_gmem_out_BVALID;
output   m_axi_gmem_out_BREADY;
input  [1:0] m_axi_gmem_out_BRESP;
input  [C_M_AXI_GMEM_OUT_ID_WIDTH - 1:0] m_axi_gmem_out_BID;
input  [C_M_AXI_GMEM_OUT_BUSER_WIDTH - 1:0] m_axi_gmem_out_BUSER;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [20:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [63:0] X;
wire   [63:0] W;
wire   [63:0] B;
wire   [63:0] G;
wire   [63:0] BE;
wire   [63:0] Y;
wire   [15:0] epsilon;
reg   [10:0] x_buf_address0;
reg    x_buf_ce0;
reg    x_buf_we0;
reg   [255:0] x_buf_d0;
wire   [255:0] x_buf_q0;
reg    gmem_in_blk_n_AR;
wire    ap_CS_fsm_state2;
reg   [15:0] epsilon_read_reg_449;
reg   [63:0] Y_read_reg_454;
reg   [63:0] BE_read_reg_459;
reg   [63:0] G_read_reg_464;
reg   [63:0] B_read_reg_469;
reg   [63:0] W_read_reg_474;
reg   [58:0] trunc_ln_reg_479;
reg   [58:0] trunc_ln1_reg_485;
reg   [4:0] hi_1_reg_495;
wire    ap_CS_fsm_state14;
wire   [13:0] sub_ln395_fu_394_p2;
reg   [13:0] sub_ln395_reg_503;
wire   [4:0] empty_46_fu_401_p2;
reg   [4:0] empty_46_reg_508;
wire   [4:0] shl_ln402_fu_424_p2;
reg   [4:0] shl_ln402_reg_513;
wire    ap_CS_fsm_state15;
wire   [4:0] add_ln402_fu_429_p2;
reg   [4:0] add_ln402_reg_518;
wire    grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_ap_start;
wire    grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_ap_done;
wire    grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_ap_idle;
wire    grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_ap_ready;
wire    grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_m_axi_gmem_in_0_AWVALID;
wire   [63:0] grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_m_axi_gmem_in_0_AWADDR;
wire   [0:0] grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_m_axi_gmem_in_0_AWID;
wire   [31:0] grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_m_axi_gmem_in_0_AWLEN;
wire   [2:0] grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_m_axi_gmem_in_0_AWSIZE;
wire   [1:0] grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_m_axi_gmem_in_0_AWBURST;
wire   [1:0] grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_m_axi_gmem_in_0_AWLOCK;
wire   [3:0] grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_m_axi_gmem_in_0_AWCACHE;
wire   [2:0] grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_m_axi_gmem_in_0_AWPROT;
wire   [3:0] grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_m_axi_gmem_in_0_AWQOS;
wire   [3:0] grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_m_axi_gmem_in_0_AWREGION;
wire   [0:0] grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_m_axi_gmem_in_0_AWUSER;
wire    grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_m_axi_gmem_in_0_WVALID;
wire   [255:0] grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_m_axi_gmem_in_0_WDATA;
wire   [31:0] grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_m_axi_gmem_in_0_WSTRB;
wire    grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_m_axi_gmem_in_0_WLAST;
wire   [0:0] grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_m_axi_gmem_in_0_WID;
wire   [0:0] grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_m_axi_gmem_in_0_WUSER;
wire    grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_m_axi_gmem_in_0_ARVALID;
wire   [63:0] grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_m_axi_gmem_in_0_ARADDR;
wire   [0:0] grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_m_axi_gmem_in_0_ARID;
wire   [31:0] grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_m_axi_gmem_in_0_ARLEN;
wire   [2:0] grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_m_axi_gmem_in_0_ARSIZE;
wire   [1:0] grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_m_axi_gmem_in_0_ARBURST;
wire   [1:0] grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_m_axi_gmem_in_0_ARLOCK;
wire   [3:0] grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_m_axi_gmem_in_0_ARCACHE;
wire   [2:0] grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_m_axi_gmem_in_0_ARPROT;
wire   [3:0] grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_m_axi_gmem_in_0_ARQOS;
wire   [3:0] grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_m_axi_gmem_in_0_ARREGION;
wire   [0:0] grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_m_axi_gmem_in_0_ARUSER;
wire    grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_m_axi_gmem_in_0_RREADY;
wire    grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_m_axi_gmem_in_0_BREADY;
wire   [10:0] grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_x_buf_address0;
wire    grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_x_buf_ce0;
wire    grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_x_buf_we0;
wire   [255:0] grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_x_buf_d0;
wire    grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_ap_start;
wire    grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_ap_done;
wire    grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_ap_idle;
wire    grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_ap_ready;
wire    grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_weight_0_AWVALID;
wire   [63:0] grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_weight_0_AWADDR;
wire   [0:0] grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_weight_0_AWID;
wire   [31:0] grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_weight_0_AWLEN;
wire   [2:0] grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_weight_0_AWSIZE;
wire   [1:0] grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_weight_0_AWBURST;
wire   [1:0] grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_weight_0_AWLOCK;
wire   [3:0] grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_weight_0_AWCACHE;
wire   [2:0] grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_weight_0_AWPROT;
wire   [3:0] grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_weight_0_AWQOS;
wire   [3:0] grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_weight_0_AWREGION;
wire   [0:0] grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_weight_0_AWUSER;
wire    grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_weight_0_WVALID;
wire   [255:0] grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_weight_0_WDATA;
wire   [31:0] grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_weight_0_WSTRB;
wire    grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_weight_0_WLAST;
wire   [0:0] grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_weight_0_WID;
wire   [0:0] grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_weight_0_WUSER;
wire    grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_weight_0_ARVALID;
wire   [63:0] grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_weight_0_ARADDR;
wire   [0:0] grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_weight_0_ARID;
wire   [31:0] grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_weight_0_ARLEN;
wire   [2:0] grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_weight_0_ARSIZE;
wire   [1:0] grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_weight_0_ARBURST;
wire   [1:0] grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_weight_0_ARLOCK;
wire   [3:0] grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_weight_0_ARCACHE;
wire   [2:0] grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_weight_0_ARPROT;
wire   [3:0] grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_weight_0_ARQOS;
wire   [3:0] grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_weight_0_ARREGION;
wire   [0:0] grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_weight_0_ARUSER;
wire    grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_weight_0_RREADY;
wire    grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_weight_0_BREADY;
wire    grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_param_0_AWVALID;
wire   [63:0] grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_param_0_AWADDR;
wire   [0:0] grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_param_0_AWID;
wire   [31:0] grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_param_0_AWLEN;
wire   [2:0] grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_param_0_AWSIZE;
wire   [1:0] grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_param_0_AWBURST;
wire   [1:0] grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_param_0_AWLOCK;
wire   [3:0] grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_param_0_AWCACHE;
wire   [2:0] grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_param_0_AWPROT;
wire   [3:0] grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_param_0_AWQOS;
wire   [3:0] grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_param_0_AWREGION;
wire   [0:0] grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_param_0_AWUSER;
wire    grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_param_0_WVALID;
wire   [255:0] grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_param_0_WDATA;
wire   [31:0] grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_param_0_WSTRB;
wire    grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_param_0_WLAST;
wire   [0:0] grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_param_0_WID;
wire   [0:0] grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_param_0_WUSER;
wire    grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_param_0_ARVALID;
wire   [63:0] grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_param_0_ARADDR;
wire   [0:0] grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_param_0_ARID;
wire   [31:0] grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_param_0_ARLEN;
wire   [2:0] grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_param_0_ARSIZE;
wire   [1:0] grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_param_0_ARBURST;
wire   [1:0] grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_param_0_ARLOCK;
wire   [3:0] grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_param_0_ARCACHE;
wire   [2:0] grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_param_0_ARPROT;
wire   [3:0] grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_param_0_ARQOS;
wire   [3:0] grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_param_0_ARREGION;
wire   [0:0] grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_param_0_ARUSER;
wire    grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_param_0_RREADY;
wire    grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_param_0_BREADY;
wire    grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_out_0_AWVALID;
wire   [63:0] grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_out_0_AWADDR;
wire   [0:0] grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_out_0_AWID;
wire   [31:0] grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_out_0_AWLEN;
wire   [2:0] grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_out_0_AWSIZE;
wire   [1:0] grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_out_0_AWBURST;
wire   [1:0] grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_out_0_AWLOCK;
wire   [3:0] grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_out_0_AWCACHE;
wire   [2:0] grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_out_0_AWPROT;
wire   [3:0] grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_out_0_AWQOS;
wire   [3:0] grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_out_0_AWREGION;
wire   [0:0] grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_out_0_AWUSER;
wire    grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_out_0_WVALID;
wire   [255:0] grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_out_0_WDATA;
wire   [31:0] grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_out_0_WSTRB;
wire    grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_out_0_WLAST;
wire   [0:0] grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_out_0_WID;
wire   [0:0] grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_out_0_WUSER;
wire    grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_out_0_ARVALID;
wire   [63:0] grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_out_0_ARADDR;
wire   [0:0] grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_out_0_ARID;
wire   [31:0] grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_out_0_ARLEN;
wire   [2:0] grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_out_0_ARSIZE;
wire   [1:0] grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_out_0_ARBURST;
wire   [1:0] grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_out_0_ARLOCK;
wire   [3:0] grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_out_0_ARCACHE;
wire   [2:0] grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_out_0_ARPROT;
wire   [3:0] grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_out_0_ARQOS;
wire   [3:0] grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_out_0_ARREGION;
wire   [0:0] grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_out_0_ARUSER;
wire    grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_out_0_RREADY;
wire    grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_out_0_BREADY;
reg   [4:0] grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_ho;
wire   [10:0] grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_x_buf_address0;
wire    grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_x_buf_ce0;
wire    grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_ap_start;
wire    grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_ap_done;
wire    grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_ap_idle;
wire    grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_ap_ready;
wire    grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_m_axi_gmem_in_0_AWVALID;
wire   [63:0] grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_m_axi_gmem_in_0_AWADDR;
wire   [0:0] grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_m_axi_gmem_in_0_AWID;
wire   [31:0] grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_m_axi_gmem_in_0_AWLEN;
wire   [2:0] grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_m_axi_gmem_in_0_AWSIZE;
wire   [1:0] grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_m_axi_gmem_in_0_AWBURST;
wire   [1:0] grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_m_axi_gmem_in_0_AWLOCK;
wire   [3:0] grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_m_axi_gmem_in_0_AWCACHE;
wire   [2:0] grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_m_axi_gmem_in_0_AWPROT;
wire   [3:0] grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_m_axi_gmem_in_0_AWQOS;
wire   [3:0] grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_m_axi_gmem_in_0_AWREGION;
wire   [0:0] grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_m_axi_gmem_in_0_AWUSER;
wire    grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_m_axi_gmem_in_0_WVALID;
wire   [255:0] grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_m_axi_gmem_in_0_WDATA;
wire   [31:0] grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_m_axi_gmem_in_0_WSTRB;
wire    grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_m_axi_gmem_in_0_WLAST;
wire   [0:0] grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_m_axi_gmem_in_0_WID;
wire   [0:0] grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_m_axi_gmem_in_0_WUSER;
wire    grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_m_axi_gmem_in_0_ARVALID;
wire   [63:0] grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_m_axi_gmem_in_0_ARADDR;
wire   [0:0] grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_m_axi_gmem_in_0_ARID;
wire   [31:0] grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_m_axi_gmem_in_0_ARLEN;
wire   [2:0] grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_m_axi_gmem_in_0_ARSIZE;
wire   [1:0] grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_m_axi_gmem_in_0_ARBURST;
wire   [1:0] grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_m_axi_gmem_in_0_ARLOCK;
wire   [3:0] grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_m_axi_gmem_in_0_ARCACHE;
wire   [2:0] grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_m_axi_gmem_in_0_ARPROT;
wire   [3:0] grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_m_axi_gmem_in_0_ARQOS;
wire   [3:0] grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_m_axi_gmem_in_0_ARREGION;
wire   [0:0] grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_m_axi_gmem_in_0_ARUSER;
wire    grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_m_axi_gmem_in_0_RREADY;
wire    grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_m_axi_gmem_in_0_BREADY;
wire   [10:0] grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_x_buf_address0;
wire    grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_x_buf_ce0;
wire    grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_x_buf_we0;
wire   [255:0] grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_x_buf_d0;
wire    gmem_in_0_AWREADY;
wire    gmem_in_0_WREADY;
reg    gmem_in_0_ARVALID;
wire    gmem_in_0_ARREADY;
reg   [63:0] gmem_in_0_ARADDR;
reg   [31:0] gmem_in_0_ARLEN;
wire    gmem_in_0_RVALID;
reg    gmem_in_0_RREADY;
wire   [255:0] gmem_in_0_RDATA;
wire   [10:0] gmem_in_0_RFIFONUM;
wire    gmem_in_0_BVALID;
reg    gmem_out_0_AWVALID;
wire    gmem_out_0_AWREADY;
reg    gmem_out_0_WVALID;
wire    gmem_out_0_WREADY;
wire    gmem_out_0_ARREADY;
wire    gmem_out_0_RVALID;
wire   [255:0] gmem_out_0_RDATA;
wire   [8:0] gmem_out_0_RFIFONUM;
wire    gmem_out_0_BVALID;
reg    gmem_out_0_BREADY;
wire    gmem_param_0_AWREADY;
wire    gmem_param_0_WREADY;
reg    gmem_param_0_ARVALID;
wire    gmem_param_0_ARREADY;
wire    gmem_param_0_RVALID;
reg    gmem_param_0_RREADY;
wire   [255:0] gmem_param_0_RDATA;
wire   [10:0] gmem_param_0_RFIFONUM;
wire    gmem_param_0_BVALID;
wire    gmem_weight_0_AWREADY;
wire    gmem_weight_0_WREADY;
reg    gmem_weight_0_ARVALID;
wire    gmem_weight_0_ARREADY;
wire    gmem_weight_0_RVALID;
reg    gmem_weight_0_RREADY;
wire   [255:0] gmem_weight_0_RDATA;
wire   [10:0] gmem_weight_0_RFIFONUM;
wire    gmem_weight_0_BVALID;
reg    grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_ap_start_reg;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state11;
reg    grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_ap_start_reg;
wire    ap_CS_fsm_state12;
wire    ap_CS_fsm_state16;
wire    ap_CS_fsm_state18;
wire    ap_CS_fsm_state20;
wire    ap_CS_fsm_state13;
wire    ap_CS_fsm_state17;
wire    ap_CS_fsm_state19;
wire    ap_CS_fsm_state21;
reg    grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_ap_start_reg;
wire   [0:0] icmp_ln394_fu_362_p2;
wire  signed [63:0] sext_ln385_fu_346_p1;
reg   [4:0] hi_fu_176;
wire   [4:0] add_ln394_1_fu_408_p2;
reg   [3:0] indvar_fu_180;
wire   [3:0] add_ln394_2_fu_368_p2;
wire   [63:0] add_ln394_fu_320_p2;
wire   [9:0] tmp_fu_382_p3;
wire   [13:0] p_shl_fu_374_p3;
wire   [13:0] zext_ln395_fu_390_p1;
reg   [20:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
reg    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
reg    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
reg    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
reg    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
reg    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
reg    ap_ST_fsm_state21_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 21'd1;
#0 grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_ap_start_reg = 1'b0;
#0 grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_ap_start_reg = 1'b0;
#0 grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_ap_start_reg = 1'b0;
#0 hi_fu_176 = 5'd0;
#0 indvar_fu_180 = 4'd0;
end

upconv_core_top_ucb0_x_buf_RAM_T2P_URAM_1R1W #(
    .DataWidth( 256 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
x_buf_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(x_buf_address0),
    .ce0(x_buf_ce0),
    .we0(x_buf_we0),
    .d0(x_buf_d0),
    .q0(x_buf_q0)
);

upconv_core_top_ucb0_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1 grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_ap_start),
    .ap_done(grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_ap_done),
    .ap_idle(grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_ap_idle),
    .ap_ready(grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_ap_ready),
    .m_axi_gmem_in_0_AWVALID(grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_m_axi_gmem_in_0_AWVALID),
    .m_axi_gmem_in_0_AWREADY(1'b0),
    .m_axi_gmem_in_0_AWADDR(grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_m_axi_gmem_in_0_AWADDR),
    .m_axi_gmem_in_0_AWID(grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_m_axi_gmem_in_0_AWID),
    .m_axi_gmem_in_0_AWLEN(grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_m_axi_gmem_in_0_AWLEN),
    .m_axi_gmem_in_0_AWSIZE(grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_m_axi_gmem_in_0_AWSIZE),
    .m_axi_gmem_in_0_AWBURST(grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_m_axi_gmem_in_0_AWBURST),
    .m_axi_gmem_in_0_AWLOCK(grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_m_axi_gmem_in_0_AWLOCK),
    .m_axi_gmem_in_0_AWCACHE(grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_m_axi_gmem_in_0_AWCACHE),
    .m_axi_gmem_in_0_AWPROT(grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_m_axi_gmem_in_0_AWPROT),
    .m_axi_gmem_in_0_AWQOS(grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_m_axi_gmem_in_0_AWQOS),
    .m_axi_gmem_in_0_AWREGION(grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_m_axi_gmem_in_0_AWREGION),
    .m_axi_gmem_in_0_AWUSER(grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_m_axi_gmem_in_0_AWUSER),
    .m_axi_gmem_in_0_WVALID(grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_m_axi_gmem_in_0_WVALID),
    .m_axi_gmem_in_0_WREADY(1'b0),
    .m_axi_gmem_in_0_WDATA(grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_m_axi_gmem_in_0_WDATA),
    .m_axi_gmem_in_0_WSTRB(grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_m_axi_gmem_in_0_WSTRB),
    .m_axi_gmem_in_0_WLAST(grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_m_axi_gmem_in_0_WLAST),
    .m_axi_gmem_in_0_WID(grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_m_axi_gmem_in_0_WID),
    .m_axi_gmem_in_0_WUSER(grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_m_axi_gmem_in_0_WUSER),
    .m_axi_gmem_in_0_ARVALID(grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_m_axi_gmem_in_0_ARVALID),
    .m_axi_gmem_in_0_ARREADY(gmem_in_0_ARREADY),
    .m_axi_gmem_in_0_ARADDR(grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_m_axi_gmem_in_0_ARADDR),
    .m_axi_gmem_in_0_ARID(grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_m_axi_gmem_in_0_ARID),
    .m_axi_gmem_in_0_ARLEN(grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_m_axi_gmem_in_0_ARLEN),
    .m_axi_gmem_in_0_ARSIZE(grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_m_axi_gmem_in_0_ARSIZE),
    .m_axi_gmem_in_0_ARBURST(grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_m_axi_gmem_in_0_ARBURST),
    .m_axi_gmem_in_0_ARLOCK(grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_m_axi_gmem_in_0_ARLOCK),
    .m_axi_gmem_in_0_ARCACHE(grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_m_axi_gmem_in_0_ARCACHE),
    .m_axi_gmem_in_0_ARPROT(grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_m_axi_gmem_in_0_ARPROT),
    .m_axi_gmem_in_0_ARQOS(grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_m_axi_gmem_in_0_ARQOS),
    .m_axi_gmem_in_0_ARREGION(grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_m_axi_gmem_in_0_ARREGION),
    .m_axi_gmem_in_0_ARUSER(grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_m_axi_gmem_in_0_ARUSER),
    .m_axi_gmem_in_0_RVALID(gmem_in_0_RVALID),
    .m_axi_gmem_in_0_RREADY(grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_m_axi_gmem_in_0_RREADY),
    .m_axi_gmem_in_0_RDATA(gmem_in_0_RDATA),
    .m_axi_gmem_in_0_RLAST(1'b0),
    .m_axi_gmem_in_0_RID(1'd0),
    .m_axi_gmem_in_0_RFIFONUM(gmem_in_0_RFIFONUM),
    .m_axi_gmem_in_0_RUSER(1'd0),
    .m_axi_gmem_in_0_RRESP(2'd0),
    .m_axi_gmem_in_0_BVALID(1'b0),
    .m_axi_gmem_in_0_BREADY(grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_m_axi_gmem_in_0_BREADY),
    .m_axi_gmem_in_0_BRESP(2'd0),
    .m_axi_gmem_in_0_BID(1'd0),
    .m_axi_gmem_in_0_BUSER(1'd0),
    .sext_ln385(trunc_ln_reg_479),
    .x_buf_address0(grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_x_buf_address0),
    .x_buf_ce0(grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_x_buf_ce0),
    .x_buf_we0(grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_x_buf_we0),
    .x_buf_d0(grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_x_buf_d0)
);

upconv_core_top_ucb0_UpConv_Fused_Row_8_16_16_960_480_s grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_ap_start),
    .ap_done(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_ap_done),
    .ap_idle(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_ap_idle),
    .ap_ready(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_ap_ready),
    .m_axi_gmem_weight_0_AWVALID(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_weight_0_AWVALID),
    .m_axi_gmem_weight_0_AWREADY(1'b0),
    .m_axi_gmem_weight_0_AWADDR(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_weight_0_AWADDR),
    .m_axi_gmem_weight_0_AWID(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_weight_0_AWID),
    .m_axi_gmem_weight_0_AWLEN(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_weight_0_AWLEN),
    .m_axi_gmem_weight_0_AWSIZE(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_weight_0_AWSIZE),
    .m_axi_gmem_weight_0_AWBURST(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_weight_0_AWBURST),
    .m_axi_gmem_weight_0_AWLOCK(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_weight_0_AWLOCK),
    .m_axi_gmem_weight_0_AWCACHE(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_weight_0_AWCACHE),
    .m_axi_gmem_weight_0_AWPROT(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_weight_0_AWPROT),
    .m_axi_gmem_weight_0_AWQOS(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_weight_0_AWQOS),
    .m_axi_gmem_weight_0_AWREGION(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_weight_0_AWREGION),
    .m_axi_gmem_weight_0_AWUSER(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_weight_0_AWUSER),
    .m_axi_gmem_weight_0_WVALID(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_weight_0_WVALID),
    .m_axi_gmem_weight_0_WREADY(1'b0),
    .m_axi_gmem_weight_0_WDATA(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_weight_0_WDATA),
    .m_axi_gmem_weight_0_WSTRB(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_weight_0_WSTRB),
    .m_axi_gmem_weight_0_WLAST(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_weight_0_WLAST),
    .m_axi_gmem_weight_0_WID(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_weight_0_WID),
    .m_axi_gmem_weight_0_WUSER(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_weight_0_WUSER),
    .m_axi_gmem_weight_0_ARVALID(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_weight_0_ARVALID),
    .m_axi_gmem_weight_0_ARREADY(gmem_weight_0_ARREADY),
    .m_axi_gmem_weight_0_ARADDR(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_weight_0_ARADDR),
    .m_axi_gmem_weight_0_ARID(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_weight_0_ARID),
    .m_axi_gmem_weight_0_ARLEN(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_weight_0_ARLEN),
    .m_axi_gmem_weight_0_ARSIZE(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_weight_0_ARSIZE),
    .m_axi_gmem_weight_0_ARBURST(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_weight_0_ARBURST),
    .m_axi_gmem_weight_0_ARLOCK(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_weight_0_ARLOCK),
    .m_axi_gmem_weight_0_ARCACHE(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_weight_0_ARCACHE),
    .m_axi_gmem_weight_0_ARPROT(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_weight_0_ARPROT),
    .m_axi_gmem_weight_0_ARQOS(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_weight_0_ARQOS),
    .m_axi_gmem_weight_0_ARREGION(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_weight_0_ARREGION),
    .m_axi_gmem_weight_0_ARUSER(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_weight_0_ARUSER),
    .m_axi_gmem_weight_0_RVALID(gmem_weight_0_RVALID),
    .m_axi_gmem_weight_0_RREADY(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_weight_0_RREADY),
    .m_axi_gmem_weight_0_RDATA(gmem_weight_0_RDATA),
    .m_axi_gmem_weight_0_RLAST(1'b0),
    .m_axi_gmem_weight_0_RID(1'd0),
    .m_axi_gmem_weight_0_RFIFONUM(gmem_weight_0_RFIFONUM),
    .m_axi_gmem_weight_0_RUSER(1'd0),
    .m_axi_gmem_weight_0_RRESP(2'd0),
    .m_axi_gmem_weight_0_BVALID(1'b0),
    .m_axi_gmem_weight_0_BREADY(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_weight_0_BREADY),
    .m_axi_gmem_weight_0_BRESP(2'd0),
    .m_axi_gmem_weight_0_BID(1'd0),
    .m_axi_gmem_weight_0_BUSER(1'd0),
    .W_ptr(W_read_reg_474),
    .m_axi_gmem_param_0_AWVALID(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_param_0_AWVALID),
    .m_axi_gmem_param_0_AWREADY(1'b0),
    .m_axi_gmem_param_0_AWADDR(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_param_0_AWADDR),
    .m_axi_gmem_param_0_AWID(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_param_0_AWID),
    .m_axi_gmem_param_0_AWLEN(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_param_0_AWLEN),
    .m_axi_gmem_param_0_AWSIZE(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_param_0_AWSIZE),
    .m_axi_gmem_param_0_AWBURST(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_param_0_AWBURST),
    .m_axi_gmem_param_0_AWLOCK(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_param_0_AWLOCK),
    .m_axi_gmem_param_0_AWCACHE(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_param_0_AWCACHE),
    .m_axi_gmem_param_0_AWPROT(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_param_0_AWPROT),
    .m_axi_gmem_param_0_AWQOS(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_param_0_AWQOS),
    .m_axi_gmem_param_0_AWREGION(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_param_0_AWREGION),
    .m_axi_gmem_param_0_AWUSER(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_param_0_AWUSER),
    .m_axi_gmem_param_0_WVALID(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_param_0_WVALID),
    .m_axi_gmem_param_0_WREADY(1'b0),
    .m_axi_gmem_param_0_WDATA(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_param_0_WDATA),
    .m_axi_gmem_param_0_WSTRB(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_param_0_WSTRB),
    .m_axi_gmem_param_0_WLAST(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_param_0_WLAST),
    .m_axi_gmem_param_0_WID(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_param_0_WID),
    .m_axi_gmem_param_0_WUSER(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_param_0_WUSER),
    .m_axi_gmem_param_0_ARVALID(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_param_0_ARVALID),
    .m_axi_gmem_param_0_ARREADY(gmem_param_0_ARREADY),
    .m_axi_gmem_param_0_ARADDR(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_param_0_ARADDR),
    .m_axi_gmem_param_0_ARID(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_param_0_ARID),
    .m_axi_gmem_param_0_ARLEN(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_param_0_ARLEN),
    .m_axi_gmem_param_0_ARSIZE(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_param_0_ARSIZE),
    .m_axi_gmem_param_0_ARBURST(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_param_0_ARBURST),
    .m_axi_gmem_param_0_ARLOCK(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_param_0_ARLOCK),
    .m_axi_gmem_param_0_ARCACHE(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_param_0_ARCACHE),
    .m_axi_gmem_param_0_ARPROT(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_param_0_ARPROT),
    .m_axi_gmem_param_0_ARQOS(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_param_0_ARQOS),
    .m_axi_gmem_param_0_ARREGION(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_param_0_ARREGION),
    .m_axi_gmem_param_0_ARUSER(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_param_0_ARUSER),
    .m_axi_gmem_param_0_RVALID(gmem_param_0_RVALID),
    .m_axi_gmem_param_0_RREADY(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_param_0_RREADY),
    .m_axi_gmem_param_0_RDATA(gmem_param_0_RDATA),
    .m_axi_gmem_param_0_RLAST(1'b0),
    .m_axi_gmem_param_0_RID(1'd0),
    .m_axi_gmem_param_0_RFIFONUM(gmem_param_0_RFIFONUM),
    .m_axi_gmem_param_0_RUSER(1'd0),
    .m_axi_gmem_param_0_RRESP(2'd0),
    .m_axi_gmem_param_0_BVALID(1'b0),
    .m_axi_gmem_param_0_BREADY(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_param_0_BREADY),
    .m_axi_gmem_param_0_BRESP(2'd0),
    .m_axi_gmem_param_0_BID(1'd0),
    .m_axi_gmem_param_0_BUSER(1'd0),
    .B_ptr(B_read_reg_469),
    .G_ptr(G_read_reg_464),
    .BE_ptr(BE_read_reg_459),
    .m_axi_gmem_out_0_AWVALID(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_out_0_AWVALID),
    .m_axi_gmem_out_0_AWREADY(gmem_out_0_AWREADY),
    .m_axi_gmem_out_0_AWADDR(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_out_0_AWADDR),
    .m_axi_gmem_out_0_AWID(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_out_0_AWID),
    .m_axi_gmem_out_0_AWLEN(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_out_0_AWLEN),
    .m_axi_gmem_out_0_AWSIZE(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_out_0_AWSIZE),
    .m_axi_gmem_out_0_AWBURST(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_out_0_AWBURST),
    .m_axi_gmem_out_0_AWLOCK(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_out_0_AWLOCK),
    .m_axi_gmem_out_0_AWCACHE(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_out_0_AWCACHE),
    .m_axi_gmem_out_0_AWPROT(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_out_0_AWPROT),
    .m_axi_gmem_out_0_AWQOS(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_out_0_AWQOS),
    .m_axi_gmem_out_0_AWREGION(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_out_0_AWREGION),
    .m_axi_gmem_out_0_AWUSER(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_out_0_AWUSER),
    .m_axi_gmem_out_0_WVALID(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_out_0_WVALID),
    .m_axi_gmem_out_0_WREADY(gmem_out_0_WREADY),
    .m_axi_gmem_out_0_WDATA(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_out_0_WDATA),
    .m_axi_gmem_out_0_WSTRB(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_out_0_WSTRB),
    .m_axi_gmem_out_0_WLAST(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_out_0_WLAST),
    .m_axi_gmem_out_0_WID(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_out_0_WID),
    .m_axi_gmem_out_0_WUSER(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_out_0_WUSER),
    .m_axi_gmem_out_0_ARVALID(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_out_0_ARVALID),
    .m_axi_gmem_out_0_ARREADY(1'b0),
    .m_axi_gmem_out_0_ARADDR(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_out_0_ARADDR),
    .m_axi_gmem_out_0_ARID(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_out_0_ARID),
    .m_axi_gmem_out_0_ARLEN(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_out_0_ARLEN),
    .m_axi_gmem_out_0_ARSIZE(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_out_0_ARSIZE),
    .m_axi_gmem_out_0_ARBURST(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_out_0_ARBURST),
    .m_axi_gmem_out_0_ARLOCK(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_out_0_ARLOCK),
    .m_axi_gmem_out_0_ARCACHE(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_out_0_ARCACHE),
    .m_axi_gmem_out_0_ARPROT(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_out_0_ARPROT),
    .m_axi_gmem_out_0_ARQOS(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_out_0_ARQOS),
    .m_axi_gmem_out_0_ARREGION(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_out_0_ARREGION),
    .m_axi_gmem_out_0_ARUSER(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_out_0_ARUSER),
    .m_axi_gmem_out_0_RVALID(1'b0),
    .m_axi_gmem_out_0_RREADY(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_out_0_RREADY),
    .m_axi_gmem_out_0_RDATA(256'd0),
    .m_axi_gmem_out_0_RLAST(1'b0),
    .m_axi_gmem_out_0_RID(1'd0),
    .m_axi_gmem_out_0_RFIFONUM(9'd0),
    .m_axi_gmem_out_0_RUSER(1'd0),
    .m_axi_gmem_out_0_RRESP(2'd0),
    .m_axi_gmem_out_0_BVALID(gmem_out_0_BVALID),
    .m_axi_gmem_out_0_BREADY(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_out_0_BREADY),
    .m_axi_gmem_out_0_BRESP(2'd0),
    .m_axi_gmem_out_0_BID(1'd0),
    .m_axi_gmem_out_0_BUSER(1'd0),
    .Y(Y_read_reg_454),
    .epsilon(epsilon_read_reg_449),
    .ho(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_ho),
    .x_buf_address0(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_x_buf_address0),
    .x_buf_ce0(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_x_buf_ce0),
    .x_buf_q0(x_buf_q0)
);

upconv_core_top_ucb0_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2 grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_ap_start),
    .ap_done(grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_ap_done),
    .ap_idle(grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_ap_idle),
    .ap_ready(grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_ap_ready),
    .m_axi_gmem_in_0_AWVALID(grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_m_axi_gmem_in_0_AWVALID),
    .m_axi_gmem_in_0_AWREADY(1'b0),
    .m_axi_gmem_in_0_AWADDR(grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_m_axi_gmem_in_0_AWADDR),
    .m_axi_gmem_in_0_AWID(grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_m_axi_gmem_in_0_AWID),
    .m_axi_gmem_in_0_AWLEN(grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_m_axi_gmem_in_0_AWLEN),
    .m_axi_gmem_in_0_AWSIZE(grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_m_axi_gmem_in_0_AWSIZE),
    .m_axi_gmem_in_0_AWBURST(grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_m_axi_gmem_in_0_AWBURST),
    .m_axi_gmem_in_0_AWLOCK(grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_m_axi_gmem_in_0_AWLOCK),
    .m_axi_gmem_in_0_AWCACHE(grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_m_axi_gmem_in_0_AWCACHE),
    .m_axi_gmem_in_0_AWPROT(grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_m_axi_gmem_in_0_AWPROT),
    .m_axi_gmem_in_0_AWQOS(grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_m_axi_gmem_in_0_AWQOS),
    .m_axi_gmem_in_0_AWREGION(grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_m_axi_gmem_in_0_AWREGION),
    .m_axi_gmem_in_0_AWUSER(grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_m_axi_gmem_in_0_AWUSER),
    .m_axi_gmem_in_0_WVALID(grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_m_axi_gmem_in_0_WVALID),
    .m_axi_gmem_in_0_WREADY(1'b0),
    .m_axi_gmem_in_0_WDATA(grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_m_axi_gmem_in_0_WDATA),
    .m_axi_gmem_in_0_WSTRB(grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_m_axi_gmem_in_0_WSTRB),
    .m_axi_gmem_in_0_WLAST(grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_m_axi_gmem_in_0_WLAST),
    .m_axi_gmem_in_0_WID(grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_m_axi_gmem_in_0_WID),
    .m_axi_gmem_in_0_WUSER(grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_m_axi_gmem_in_0_WUSER),
    .m_axi_gmem_in_0_ARVALID(grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_m_axi_gmem_in_0_ARVALID),
    .m_axi_gmem_in_0_ARREADY(gmem_in_0_ARREADY),
    .m_axi_gmem_in_0_ARADDR(grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_m_axi_gmem_in_0_ARADDR),
    .m_axi_gmem_in_0_ARID(grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_m_axi_gmem_in_0_ARID),
    .m_axi_gmem_in_0_ARLEN(grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_m_axi_gmem_in_0_ARLEN),
    .m_axi_gmem_in_0_ARSIZE(grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_m_axi_gmem_in_0_ARSIZE),
    .m_axi_gmem_in_0_ARBURST(grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_m_axi_gmem_in_0_ARBURST),
    .m_axi_gmem_in_0_ARLOCK(grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_m_axi_gmem_in_0_ARLOCK),
    .m_axi_gmem_in_0_ARCACHE(grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_m_axi_gmem_in_0_ARCACHE),
    .m_axi_gmem_in_0_ARPROT(grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_m_axi_gmem_in_0_ARPROT),
    .m_axi_gmem_in_0_ARQOS(grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_m_axi_gmem_in_0_ARQOS),
    .m_axi_gmem_in_0_ARREGION(grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_m_axi_gmem_in_0_ARREGION),
    .m_axi_gmem_in_0_ARUSER(grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_m_axi_gmem_in_0_ARUSER),
    .m_axi_gmem_in_0_RVALID(gmem_in_0_RVALID),
    .m_axi_gmem_in_0_RREADY(grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_m_axi_gmem_in_0_RREADY),
    .m_axi_gmem_in_0_RDATA(gmem_in_0_RDATA),
    .m_axi_gmem_in_0_RLAST(1'b0),
    .m_axi_gmem_in_0_RID(1'd0),
    .m_axi_gmem_in_0_RFIFONUM(gmem_in_0_RFIFONUM),
    .m_axi_gmem_in_0_RUSER(1'd0),
    .m_axi_gmem_in_0_RRESP(2'd0),
    .m_axi_gmem_in_0_BVALID(1'b0),
    .m_axi_gmem_in_0_BREADY(grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_m_axi_gmem_in_0_BREADY),
    .m_axi_gmem_in_0_BRESP(2'd0),
    .m_axi_gmem_in_0_BID(1'd0),
    .m_axi_gmem_in_0_BUSER(1'd0),
    .empty(empty_46_reg_508),
    .mul_ln395(sub_ln395_reg_503),
    .sext_ln394(trunc_ln1_reg_485),
    .x_buf_address0(grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_x_buf_address0),
    .x_buf_ce0(grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_x_buf_ce0),
    .x_buf_we0(grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_x_buf_we0),
    .x_buf_d0(grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_x_buf_d0)
);

upconv_core_top_ucb0_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .X(X),
    .W(W),
    .B(B),
    .G(G),
    .BE(BE),
    .Y(Y),
    .epsilon(epsilon),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

upconv_core_top_ucb0_gmem_in_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 7 ),
    .MAX_READ_BURST_LENGTH( 64 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM_IN_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM_IN_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM_IN_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM_IN_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM_IN_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM_IN_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM_IN_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM_IN_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM_IN_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM_IN_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM_IN_CACHE_VALUE ),
    .CH0_USER_RFIFONUM_WIDTH( 11 ),
    .CH0_USER_DW( 256 ),
    .CH0_USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 0 ))
gmem_in_m_axi_U(
    .AWVALID(m_axi_gmem_in_AWVALID),
    .AWREADY(m_axi_gmem_in_AWREADY),
    .AWADDR(m_axi_gmem_in_AWADDR),
    .AWID(m_axi_gmem_in_AWID),
    .AWLEN(m_axi_gmem_in_AWLEN),
    .AWSIZE(m_axi_gmem_in_AWSIZE),
    .AWBURST(m_axi_gmem_in_AWBURST),
    .AWLOCK(m_axi_gmem_in_AWLOCK),
    .AWCACHE(m_axi_gmem_in_AWCACHE),
    .AWPROT(m_axi_gmem_in_AWPROT),
    .AWQOS(m_axi_gmem_in_AWQOS),
    .AWREGION(m_axi_gmem_in_AWREGION),
    .AWUSER(m_axi_gmem_in_AWUSER),
    .WVALID(m_axi_gmem_in_WVALID),
    .WREADY(m_axi_gmem_in_WREADY),
    .WDATA(m_axi_gmem_in_WDATA),
    .WSTRB(m_axi_gmem_in_WSTRB),
    .WLAST(m_axi_gmem_in_WLAST),
    .WID(m_axi_gmem_in_WID),
    .WUSER(m_axi_gmem_in_WUSER),
    .ARVALID(m_axi_gmem_in_ARVALID),
    .ARREADY(m_axi_gmem_in_ARREADY),
    .ARADDR(m_axi_gmem_in_ARADDR),
    .ARID(m_axi_gmem_in_ARID),
    .ARLEN(m_axi_gmem_in_ARLEN),
    .ARSIZE(m_axi_gmem_in_ARSIZE),
    .ARBURST(m_axi_gmem_in_ARBURST),
    .ARLOCK(m_axi_gmem_in_ARLOCK),
    .ARCACHE(m_axi_gmem_in_ARCACHE),
    .ARPROT(m_axi_gmem_in_ARPROT),
    .ARQOS(m_axi_gmem_in_ARQOS),
    .ARREGION(m_axi_gmem_in_ARREGION),
    .ARUSER(m_axi_gmem_in_ARUSER),
    .RVALID(m_axi_gmem_in_RVALID),
    .RREADY(m_axi_gmem_in_RREADY),
    .RDATA(m_axi_gmem_in_RDATA),
    .RLAST(m_axi_gmem_in_RLAST),
    .RID(m_axi_gmem_in_RID),
    .RUSER(m_axi_gmem_in_RUSER),
    .RRESP(m_axi_gmem_in_RRESP),
    .BVALID(m_axi_gmem_in_BVALID),
    .BREADY(m_axi_gmem_in_BREADY),
    .BRESP(m_axi_gmem_in_BRESP),
    .BID(m_axi_gmem_in_BID),
    .BUSER(m_axi_gmem_in_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_CH0_ARVALID(gmem_in_0_ARVALID),
    .I_CH0_ARREADY(gmem_in_0_ARREADY),
    .I_CH0_ARADDR(gmem_in_0_ARADDR),
    .I_CH0_ARLEN(gmem_in_0_ARLEN),
    .I_CH0_RVALID(gmem_in_0_RVALID),
    .I_CH0_RREADY(gmem_in_0_RREADY),
    .I_CH0_RDATA(gmem_in_0_RDATA),
    .I_CH0_RFIFONUM(gmem_in_0_RFIFONUM),
    .I_CH0_AWVALID(1'b0),
    .I_CH0_AWREADY(gmem_in_0_AWREADY),
    .I_CH0_AWADDR(64'd0),
    .I_CH0_AWLEN(32'd0),
    .I_CH0_WVALID(1'b0),
    .I_CH0_WREADY(gmem_in_0_WREADY),
    .I_CH0_WDATA(256'd0),
    .I_CH0_WSTRB(32'd0),
    .I_CH0_BVALID(gmem_in_0_BVALID),
    .I_CH0_BREADY(1'b0)
);

upconv_core_top_ucb0_gmem_out_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 4 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 64 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM_OUT_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM_OUT_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM_OUT_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM_OUT_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM_OUT_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM_OUT_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM_OUT_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM_OUT_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM_OUT_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM_OUT_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM_OUT_CACHE_VALUE ),
    .CH0_USER_RFIFONUM_WIDTH( 9 ),
    .CH0_USER_DW( 256 ),
    .CH0_USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 0 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
gmem_out_m_axi_U(
    .AWVALID(m_axi_gmem_out_AWVALID),
    .AWREADY(m_axi_gmem_out_AWREADY),
    .AWADDR(m_axi_gmem_out_AWADDR),
    .AWID(m_axi_gmem_out_AWID),
    .AWLEN(m_axi_gmem_out_AWLEN),
    .AWSIZE(m_axi_gmem_out_AWSIZE),
    .AWBURST(m_axi_gmem_out_AWBURST),
    .AWLOCK(m_axi_gmem_out_AWLOCK),
    .AWCACHE(m_axi_gmem_out_AWCACHE),
    .AWPROT(m_axi_gmem_out_AWPROT),
    .AWQOS(m_axi_gmem_out_AWQOS),
    .AWREGION(m_axi_gmem_out_AWREGION),
    .AWUSER(m_axi_gmem_out_AWUSER),
    .WVALID(m_axi_gmem_out_WVALID),
    .WREADY(m_axi_gmem_out_WREADY),
    .WDATA(m_axi_gmem_out_WDATA),
    .WSTRB(m_axi_gmem_out_WSTRB),
    .WLAST(m_axi_gmem_out_WLAST),
    .WID(m_axi_gmem_out_WID),
    .WUSER(m_axi_gmem_out_WUSER),
    .ARVALID(m_axi_gmem_out_ARVALID),
    .ARREADY(m_axi_gmem_out_ARREADY),
    .ARADDR(m_axi_gmem_out_ARADDR),
    .ARID(m_axi_gmem_out_ARID),
    .ARLEN(m_axi_gmem_out_ARLEN),
    .ARSIZE(m_axi_gmem_out_ARSIZE),
    .ARBURST(m_axi_gmem_out_ARBURST),
    .ARLOCK(m_axi_gmem_out_ARLOCK),
    .ARCACHE(m_axi_gmem_out_ARCACHE),
    .ARPROT(m_axi_gmem_out_ARPROT),
    .ARQOS(m_axi_gmem_out_ARQOS),
    .ARREGION(m_axi_gmem_out_ARREGION),
    .ARUSER(m_axi_gmem_out_ARUSER),
    .RVALID(m_axi_gmem_out_RVALID),
    .RREADY(m_axi_gmem_out_RREADY),
    .RDATA(m_axi_gmem_out_RDATA),
    .RLAST(m_axi_gmem_out_RLAST),
    .RID(m_axi_gmem_out_RID),
    .RUSER(m_axi_gmem_out_RUSER),
    .RRESP(m_axi_gmem_out_RRESP),
    .BVALID(m_axi_gmem_out_BVALID),
    .BREADY(m_axi_gmem_out_BREADY),
    .BRESP(m_axi_gmem_out_BRESP),
    .BID(m_axi_gmem_out_BID),
    .BUSER(m_axi_gmem_out_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_CH0_ARVALID(1'b0),
    .I_CH0_ARREADY(gmem_out_0_ARREADY),
    .I_CH0_ARADDR(64'd0),
    .I_CH0_ARLEN(32'd0),
    .I_CH0_RVALID(gmem_out_0_RVALID),
    .I_CH0_RREADY(1'b0),
    .I_CH0_RDATA(gmem_out_0_RDATA),
    .I_CH0_RFIFONUM(gmem_out_0_RFIFONUM),
    .I_CH0_AWVALID(gmem_out_0_AWVALID),
    .I_CH0_AWREADY(gmem_out_0_AWREADY),
    .I_CH0_AWADDR(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_out_0_AWADDR),
    .I_CH0_AWLEN(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_out_0_AWLEN),
    .I_CH0_WVALID(gmem_out_0_WVALID),
    .I_CH0_WREADY(gmem_out_0_WREADY),
    .I_CH0_WDATA(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_out_0_WDATA),
    .I_CH0_WSTRB(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_out_0_WSTRB),
    .I_CH0_BVALID(gmem_out_0_BVALID),
    .I_CH0_BREADY(gmem_out_0_BREADY)
);

upconv_core_top_ucb0_gmem_param_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 7 ),
    .MAX_READ_BURST_LENGTH( 64 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM_PARAM_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM_PARAM_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM_PARAM_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM_PARAM_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM_PARAM_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM_PARAM_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM_PARAM_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM_PARAM_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM_PARAM_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM_PARAM_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM_PARAM_CACHE_VALUE ),
    .CH0_USER_RFIFONUM_WIDTH( 11 ),
    .CH0_USER_DW( 256 ),
    .CH0_USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 0 ))
gmem_param_m_axi_U(
    .AWVALID(m_axi_gmem_param_AWVALID),
    .AWREADY(m_axi_gmem_param_AWREADY),
    .AWADDR(m_axi_gmem_param_AWADDR),
    .AWID(m_axi_gmem_param_AWID),
    .AWLEN(m_axi_gmem_param_AWLEN),
    .AWSIZE(m_axi_gmem_param_AWSIZE),
    .AWBURST(m_axi_gmem_param_AWBURST),
    .AWLOCK(m_axi_gmem_param_AWLOCK),
    .AWCACHE(m_axi_gmem_param_AWCACHE),
    .AWPROT(m_axi_gmem_param_AWPROT),
    .AWQOS(m_axi_gmem_param_AWQOS),
    .AWREGION(m_axi_gmem_param_AWREGION),
    .AWUSER(m_axi_gmem_param_AWUSER),
    .WVALID(m_axi_gmem_param_WVALID),
    .WREADY(m_axi_gmem_param_WREADY),
    .WDATA(m_axi_gmem_param_WDATA),
    .WSTRB(m_axi_gmem_param_WSTRB),
    .WLAST(m_axi_gmem_param_WLAST),
    .WID(m_axi_gmem_param_WID),
    .WUSER(m_axi_gmem_param_WUSER),
    .ARVALID(m_axi_gmem_param_ARVALID),
    .ARREADY(m_axi_gmem_param_ARREADY),
    .ARADDR(m_axi_gmem_param_ARADDR),
    .ARID(m_axi_gmem_param_ARID),
    .ARLEN(m_axi_gmem_param_ARLEN),
    .ARSIZE(m_axi_gmem_param_ARSIZE),
    .ARBURST(m_axi_gmem_param_ARBURST),
    .ARLOCK(m_axi_gmem_param_ARLOCK),
    .ARCACHE(m_axi_gmem_param_ARCACHE),
    .ARPROT(m_axi_gmem_param_ARPROT),
    .ARQOS(m_axi_gmem_param_ARQOS),
    .ARREGION(m_axi_gmem_param_ARREGION),
    .ARUSER(m_axi_gmem_param_ARUSER),
    .RVALID(m_axi_gmem_param_RVALID),
    .RREADY(m_axi_gmem_param_RREADY),
    .RDATA(m_axi_gmem_param_RDATA),
    .RLAST(m_axi_gmem_param_RLAST),
    .RID(m_axi_gmem_param_RID),
    .RUSER(m_axi_gmem_param_RUSER),
    .RRESP(m_axi_gmem_param_RRESP),
    .BVALID(m_axi_gmem_param_BVALID),
    .BREADY(m_axi_gmem_param_BREADY),
    .BRESP(m_axi_gmem_param_BRESP),
    .BID(m_axi_gmem_param_BID),
    .BUSER(m_axi_gmem_param_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_CH0_ARVALID(gmem_param_0_ARVALID),
    .I_CH0_ARREADY(gmem_param_0_ARREADY),
    .I_CH0_ARADDR(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_param_0_ARADDR),
    .I_CH0_ARLEN(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_param_0_ARLEN),
    .I_CH0_RVALID(gmem_param_0_RVALID),
    .I_CH0_RREADY(gmem_param_0_RREADY),
    .I_CH0_RDATA(gmem_param_0_RDATA),
    .I_CH0_RFIFONUM(gmem_param_0_RFIFONUM),
    .I_CH0_AWVALID(1'b0),
    .I_CH0_AWREADY(gmem_param_0_AWREADY),
    .I_CH0_AWADDR(64'd0),
    .I_CH0_AWLEN(32'd0),
    .I_CH0_WVALID(1'b0),
    .I_CH0_WREADY(gmem_param_0_WREADY),
    .I_CH0_WDATA(256'd0),
    .I_CH0_WSTRB(32'd0),
    .I_CH0_BVALID(gmem_param_0_BVALID),
    .I_CH0_BREADY(1'b0)
);

upconv_core_top_ucb0_gmem_weight_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 7 ),
    .MAX_READ_BURST_LENGTH( 64 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM_WEIGHT_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM_WEIGHT_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM_WEIGHT_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM_WEIGHT_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM_WEIGHT_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM_WEIGHT_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM_WEIGHT_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM_WEIGHT_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM_WEIGHT_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM_WEIGHT_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM_WEIGHT_CACHE_VALUE ),
    .CH0_USER_RFIFONUM_WIDTH( 11 ),
    .CH0_USER_DW( 256 ),
    .CH0_USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 0 ))
gmem_weight_m_axi_U(
    .AWVALID(m_axi_gmem_weight_AWVALID),
    .AWREADY(m_axi_gmem_weight_AWREADY),
    .AWADDR(m_axi_gmem_weight_AWADDR),
    .AWID(m_axi_gmem_weight_AWID),
    .AWLEN(m_axi_gmem_weight_AWLEN),
    .AWSIZE(m_axi_gmem_weight_AWSIZE),
    .AWBURST(m_axi_gmem_weight_AWBURST),
    .AWLOCK(m_axi_gmem_weight_AWLOCK),
    .AWCACHE(m_axi_gmem_weight_AWCACHE),
    .AWPROT(m_axi_gmem_weight_AWPROT),
    .AWQOS(m_axi_gmem_weight_AWQOS),
    .AWREGION(m_axi_gmem_weight_AWREGION),
    .AWUSER(m_axi_gmem_weight_AWUSER),
    .WVALID(m_axi_gmem_weight_WVALID),
    .WREADY(m_axi_gmem_weight_WREADY),
    .WDATA(m_axi_gmem_weight_WDATA),
    .WSTRB(m_axi_gmem_weight_WSTRB),
    .WLAST(m_axi_gmem_weight_WLAST),
    .WID(m_axi_gmem_weight_WID),
    .WUSER(m_axi_gmem_weight_WUSER),
    .ARVALID(m_axi_gmem_weight_ARVALID),
    .ARREADY(m_axi_gmem_weight_ARREADY),
    .ARADDR(m_axi_gmem_weight_ARADDR),
    .ARID(m_axi_gmem_weight_ARID),
    .ARLEN(m_axi_gmem_weight_ARLEN),
    .ARSIZE(m_axi_gmem_weight_ARSIZE),
    .ARBURST(m_axi_gmem_weight_ARBURST),
    .ARLOCK(m_axi_gmem_weight_ARLOCK),
    .ARCACHE(m_axi_gmem_weight_ARCACHE),
    .ARPROT(m_axi_gmem_weight_ARPROT),
    .ARQOS(m_axi_gmem_weight_ARQOS),
    .ARREGION(m_axi_gmem_weight_ARREGION),
    .ARUSER(m_axi_gmem_weight_ARUSER),
    .RVALID(m_axi_gmem_weight_RVALID),
    .RREADY(m_axi_gmem_weight_RREADY),
    .RDATA(m_axi_gmem_weight_RDATA),
    .RLAST(m_axi_gmem_weight_RLAST),
    .RID(m_axi_gmem_weight_RID),
    .RUSER(m_axi_gmem_weight_RUSER),
    .RRESP(m_axi_gmem_weight_RRESP),
    .BVALID(m_axi_gmem_weight_BVALID),
    .BREADY(m_axi_gmem_weight_BREADY),
    .BRESP(m_axi_gmem_weight_BRESP),
    .BID(m_axi_gmem_weight_BID),
    .BUSER(m_axi_gmem_weight_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_CH0_ARVALID(gmem_weight_0_ARVALID),
    .I_CH0_ARREADY(gmem_weight_0_ARREADY),
    .I_CH0_ARADDR(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_weight_0_ARADDR),
    .I_CH0_ARLEN(grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_weight_0_ARLEN),
    .I_CH0_RVALID(gmem_weight_0_RVALID),
    .I_CH0_RREADY(gmem_weight_0_RREADY),
    .I_CH0_RDATA(gmem_weight_0_RDATA),
    .I_CH0_RFIFONUM(gmem_weight_0_RFIFONUM),
    .I_CH0_AWVALID(1'b0),
    .I_CH0_AWREADY(gmem_weight_0_AWREADY),
    .I_CH0_AWADDR(64'd0),
    .I_CH0_AWLEN(32'd0),
    .I_CH0_WVALID(1'b0),
    .I_CH0_WREADY(gmem_weight_0_WREADY),
    .I_CH0_WDATA(256'd0),
    .I_CH0_WSTRB(32'd0),
    .I_CH0_BVALID(gmem_weight_0_BVALID),
    .I_CH0_BREADY(1'b0)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state12))) begin
            grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_ap_start_reg <= 1'b1;
        end else if ((grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_ap_ready == 1'b1)) begin
            grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state10)) begin
            grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_ap_start_reg <= 1'b1;
        end else if ((grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_ap_ready == 1'b1)) begin
            grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln394_fu_362_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state14))) begin
            grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_ap_start_reg <= 1'b1;
        end else if ((grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_ap_ready == 1'b1)) begin
            grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        hi_fu_176 <= 5'd1;
    end else if (((icmp_ln394_fu_362_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state14))) begin
        hi_fu_176 <= add_ln394_1_fu_408_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        indvar_fu_180 <= 4'd0;
    end else if (((icmp_ln394_fu_362_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state14))) begin
        indvar_fu_180 <= add_ln394_2_fu_368_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        BE_read_reg_459 <= BE;
        B_read_reg_469 <= B;
        G_read_reg_464 <= G;
        W_read_reg_474 <= W;
        Y_read_reg_454 <= Y;
        epsilon_read_reg_449 <= epsilon;
        trunc_ln1_reg_485 <= {{add_ln394_fu_320_p2[63:5]}};
        trunc_ln_reg_479 <= {{X[63:5]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        add_ln402_reg_518 <= add_ln402_fu_429_p2;
        shl_ln402_reg_513 <= shl_ln402_fu_424_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        empty_46_reg_508 <= empty_46_fu_401_p2;
        hi_1_reg_495 <= hi_fu_176;
        sub_ln395_reg_503[13 : 6] <= sub_ln395_fu_394_p2[13 : 6];
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

always @ (*) begin
    if ((grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_ap_done == 1'b0)) begin
        ap_ST_fsm_state11_blk = 1'b1;
    end else begin
        ap_ST_fsm_state11_blk = 1'b0;
    end
end

assign ap_ST_fsm_state12_blk = 1'b0;

always @ (*) begin
    if ((grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_ap_done == 1'b0)) begin
        ap_ST_fsm_state13_blk = 1'b1;
    end else begin
        ap_ST_fsm_state13_blk = 1'b0;
    end
end

assign ap_ST_fsm_state14_blk = 1'b0;

always @ (*) begin
    if ((grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_ap_done == 1'b0)) begin
        ap_ST_fsm_state15_blk = 1'b1;
    end else begin
        ap_ST_fsm_state15_blk = 1'b0;
    end
end

assign ap_ST_fsm_state16_blk = 1'b0;

always @ (*) begin
    if ((grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_ap_done == 1'b0)) begin
        ap_ST_fsm_state17_blk = 1'b1;
    end else begin
        ap_ST_fsm_state17_blk = 1'b0;
    end
end

assign ap_ST_fsm_state18_blk = 1'b0;

always @ (*) begin
    if ((grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_ap_done == 1'b0)) begin
        ap_ST_fsm_state19_blk = 1'b1;
    end else begin
        ap_ST_fsm_state19_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

always @ (*) begin
    if ((grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_ap_done == 1'b0)) begin
        ap_ST_fsm_state21_blk = 1'b1;
    end else begin
        ap_ST_fsm_state21_blk = 1'b0;
    end
end

always @ (*) begin
    if ((gmem_in_0_ARREADY == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state21))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state21))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((gmem_in_0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        gmem_in_0_ARADDR = sext_ln385_fu_346_p1;
    end else if (((1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14))) begin
        gmem_in_0_ARADDR = grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_m_axi_gmem_in_0_ARADDR;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        gmem_in_0_ARADDR = grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_m_axi_gmem_in_0_ARADDR;
    end else begin
        gmem_in_0_ARADDR = 'bx;
    end
end

always @ (*) begin
    if (((gmem_in_0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        gmem_in_0_ARLEN = 64'd960;
    end else if (((1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14))) begin
        gmem_in_0_ARLEN = grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_m_axi_gmem_in_0_ARLEN;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        gmem_in_0_ARLEN = grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_m_axi_gmem_in_0_ARLEN;
    end else begin
        gmem_in_0_ARLEN = 'bx;
    end
end

always @ (*) begin
    if (((gmem_in_0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        gmem_in_0_ARVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14))) begin
        gmem_in_0_ARVALID = grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_m_axi_gmem_in_0_ARVALID;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        gmem_in_0_ARVALID = grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_m_axi_gmem_in_0_ARVALID;
    end else begin
        gmem_in_0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14))) begin
        gmem_in_0_RREADY = grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_m_axi_gmem_in_0_RREADY;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        gmem_in_0_RREADY = grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_m_axi_gmem_in_0_RREADY;
    end else begin
        gmem_in_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        gmem_in_blk_n_AR = m_axi_gmem_in_ARREADY;
    end else begin
        gmem_in_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state12))) begin
        gmem_out_0_AWVALID = grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_out_0_AWVALID;
    end else begin
        gmem_out_0_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state12))) begin
        gmem_out_0_BREADY = grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_out_0_BREADY;
    end else begin
        gmem_out_0_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state12))) begin
        gmem_out_0_WVALID = grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_out_0_WVALID;
    end else begin
        gmem_out_0_WVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state12))) begin
        gmem_param_0_ARVALID = grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_param_0_ARVALID;
    end else begin
        gmem_param_0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state12))) begin
        gmem_param_0_RREADY = grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_param_0_RREADY;
    end else begin
        gmem_param_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state12))) begin
        gmem_weight_0_ARVALID = grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_weight_0_ARVALID;
    end else begin
        gmem_weight_0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state12))) begin
        gmem_weight_0_RREADY = grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_m_axi_gmem_weight_0_RREADY;
    end else begin
        gmem_weight_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_ho = 5'd31;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_ho = shl_ln402_reg_513;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_ho = add_ln402_reg_518;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_ho = 5'd0;
    end else begin
        grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_ho = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        x_buf_address0 = grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_x_buf_address0;
    end else if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state13))) begin
        x_buf_address0 = grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_x_buf_address0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        x_buf_address0 = grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_x_buf_address0;
    end else begin
        x_buf_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        x_buf_ce0 = grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_x_buf_ce0;
    end else if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state13))) begin
        x_buf_ce0 = grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_x_buf_ce0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        x_buf_ce0 = grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_x_buf_ce0;
    end else begin
        x_buf_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        x_buf_d0 = grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_x_buf_d0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        x_buf_d0 = grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_x_buf_d0;
    end else begin
        x_buf_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        x_buf_we0 = grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_x_buf_we0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        x_buf_we0 = grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_x_buf_we0;
    end else begin
        x_buf_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((gmem_in_0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            if (((grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            if (((grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state14 : begin
            if (((icmp_ln394_fu_362_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state14))) begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        ap_ST_fsm_state15 : begin
            if (((grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            if (((grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state17))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            if (((grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state19))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            if (((grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state21))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln394_1_fu_408_p2 = (hi_fu_176 + 5'd1);

assign add_ln394_2_fu_368_p2 = (indvar_fu_180 + 4'd1);

assign add_ln394_fu_320_p2 = (X + 64'd30720);

assign add_ln402_fu_429_p2 = ($signed(shl_ln402_fu_424_p2) + $signed(5'd31));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign empty_46_fu_401_p2 = hi_fu_176 << 5'd4;

assign grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_ap_start = grp_UpConv_Fused_Row_8_16_16_960_480_s_fu_242_ap_start_reg;

assign grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_ap_start = grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW0_VITIS_LOOP_386_1_fu_233_ap_start_reg;

assign grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_ap_start = grp_upconv_core_top_ucb0_Pipeline_LOAD_ROW_VITIS_LOOP_397_2_fu_299_ap_start_reg;

assign icmp_ln394_fu_362_p2 = ((hi_fu_176 == 5'd16) ? 1'b1 : 1'b0);

assign p_shl_fu_374_p3 = {{indvar_fu_180}, {10'd0}};

assign sext_ln385_fu_346_p1 = $signed(trunc_ln_reg_479);

assign shl_ln402_fu_424_p2 = hi_1_reg_495 << 5'd1;

assign sub_ln395_fu_394_p2 = (p_shl_fu_374_p3 - zext_ln395_fu_390_p1);

assign tmp_fu_382_p3 = {{indvar_fu_180}, {6'd0}};

assign zext_ln395_fu_390_p1 = tmp_fu_382_p3;

always @ (posedge ap_clk) begin
    sub_ln395_reg_503[5:0] <= 6'b000000;
end

endmodule //upconv_core_top_ucb0
