// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module upconv_core_top_UpConv_Fused_Row_8_16_16_960_480_Pipeline_LOAD_PARAMS (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem_param_0_AWVALID,
        m_axi_gmem_param_0_AWREADY,
        m_axi_gmem_param_0_AWADDR,
        m_axi_gmem_param_0_AWID,
        m_axi_gmem_param_0_AWLEN,
        m_axi_gmem_param_0_AWSIZE,
        m_axi_gmem_param_0_AWBURST,
        m_axi_gmem_param_0_AWLOCK,
        m_axi_gmem_param_0_AWCACHE,
        m_axi_gmem_param_0_AWPROT,
        m_axi_gmem_param_0_AWQOS,
        m_axi_gmem_param_0_AWREGION,
        m_axi_gmem_param_0_AWUSER,
        m_axi_gmem_param_0_WVALID,
        m_axi_gmem_param_0_WREADY,
        m_axi_gmem_param_0_WDATA,
        m_axi_gmem_param_0_WSTRB,
        m_axi_gmem_param_0_WLAST,
        m_axi_gmem_param_0_WID,
        m_axi_gmem_param_0_WUSER,
        m_axi_gmem_param_0_ARVALID,
        m_axi_gmem_param_0_ARREADY,
        m_axi_gmem_param_0_ARADDR,
        m_axi_gmem_param_0_ARID,
        m_axi_gmem_param_0_ARLEN,
        m_axi_gmem_param_0_ARSIZE,
        m_axi_gmem_param_0_ARBURST,
        m_axi_gmem_param_0_ARLOCK,
        m_axi_gmem_param_0_ARCACHE,
        m_axi_gmem_param_0_ARPROT,
        m_axi_gmem_param_0_ARQOS,
        m_axi_gmem_param_0_ARREGION,
        m_axi_gmem_param_0_ARUSER,
        m_axi_gmem_param_0_RVALID,
        m_axi_gmem_param_0_RREADY,
        m_axi_gmem_param_0_RDATA,
        m_axi_gmem_param_0_RLAST,
        m_axi_gmem_param_0_RID,
        m_axi_gmem_param_0_RFIFONUM,
        m_axi_gmem_param_0_RUSER,
        m_axi_gmem_param_0_RRESP,
        m_axi_gmem_param_0_BVALID,
        m_axi_gmem_param_0_BREADY,
        m_axi_gmem_param_0_BRESP,
        m_axi_gmem_param_0_BID,
        m_axi_gmem_param_0_BUSER,
        b_buf_address0,
        b_buf_ce0,
        b_buf_we0,
        b_buf_d0,
        sext_ln228,
        g_buf_address0,
        g_buf_ce0,
        g_buf_we0,
        g_buf_d0,
        sext_ln228_5,
        be_buf_address0,
        be_buf_ce0,
        be_buf_we0,
        be_buf_d0,
        sext_ln228_6
);

parameter    ap_ST_fsm_pp0_stage0 = 3'd1;
parameter    ap_ST_fsm_pp0_stage1 = 3'd2;
parameter    ap_ST_fsm_pp0_stage2 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem_param_0_AWVALID;
input   m_axi_gmem_param_0_AWREADY;
output  [63:0] m_axi_gmem_param_0_AWADDR;
output  [0:0] m_axi_gmem_param_0_AWID;
output  [31:0] m_axi_gmem_param_0_AWLEN;
output  [2:0] m_axi_gmem_param_0_AWSIZE;
output  [1:0] m_axi_gmem_param_0_AWBURST;
output  [1:0] m_axi_gmem_param_0_AWLOCK;
output  [3:0] m_axi_gmem_param_0_AWCACHE;
output  [2:0] m_axi_gmem_param_0_AWPROT;
output  [3:0] m_axi_gmem_param_0_AWQOS;
output  [3:0] m_axi_gmem_param_0_AWREGION;
output  [0:0] m_axi_gmem_param_0_AWUSER;
output   m_axi_gmem_param_0_WVALID;
input   m_axi_gmem_param_0_WREADY;
output  [255:0] m_axi_gmem_param_0_WDATA;
output  [31:0] m_axi_gmem_param_0_WSTRB;
output   m_axi_gmem_param_0_WLAST;
output  [0:0] m_axi_gmem_param_0_WID;
output  [0:0] m_axi_gmem_param_0_WUSER;
output   m_axi_gmem_param_0_ARVALID;
input   m_axi_gmem_param_0_ARREADY;
output  [63:0] m_axi_gmem_param_0_ARADDR;
output  [0:0] m_axi_gmem_param_0_ARID;
output  [31:0] m_axi_gmem_param_0_ARLEN;
output  [2:0] m_axi_gmem_param_0_ARSIZE;
output  [1:0] m_axi_gmem_param_0_ARBURST;
output  [1:0] m_axi_gmem_param_0_ARLOCK;
output  [3:0] m_axi_gmem_param_0_ARCACHE;
output  [2:0] m_axi_gmem_param_0_ARPROT;
output  [3:0] m_axi_gmem_param_0_ARQOS;
output  [3:0] m_axi_gmem_param_0_ARREGION;
output  [0:0] m_axi_gmem_param_0_ARUSER;
input   m_axi_gmem_param_0_RVALID;
output   m_axi_gmem_param_0_RREADY;
input  [255:0] m_axi_gmem_param_0_RDATA;
input   m_axi_gmem_param_0_RLAST;
input  [0:0] m_axi_gmem_param_0_RID;
input  [10:0] m_axi_gmem_param_0_RFIFONUM;
input  [0:0] m_axi_gmem_param_0_RUSER;
input  [1:0] m_axi_gmem_param_0_RRESP;
input   m_axi_gmem_param_0_BVALID;
output   m_axi_gmem_param_0_BREADY;
input  [1:0] m_axi_gmem_param_0_BRESP;
input  [0:0] m_axi_gmem_param_0_BID;
input  [0:0] m_axi_gmem_param_0_BUSER;
output  [4:0] b_buf_address0;
output   b_buf_ce0;
output   b_buf_we0;
output  [255:0] b_buf_d0;
input  [58:0] sext_ln228;
output  [4:0] g_buf_address0;
output   g_buf_ce0;
output   g_buf_we0;
output  [255:0] g_buf_d0;
input  [58:0] sext_ln228_5;
output  [4:0] be_buf_address0;
output   be_buf_ce0;
output   be_buf_we0;
output  [255:0] be_buf_d0;
input  [58:0] sext_ln228_6;

reg ap_idle;
reg m_axi_gmem_param_0_ARVALID;
reg[63:0] m_axi_gmem_param_0_ARADDR;
reg m_axi_gmem_param_0_RREADY;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage2;
reg   [0:0] icmp_ln228_reg_274;
reg    ap_block_state3_io_grp2;
reg    ap_block_pp0_stage2_subdone_grp2_done_reg;
reg    ap_block_pp0_stage2_subdone_grp2;
reg    ap_block_pp0_stage2_subdone;
reg    ap_enable_reg_pp0_iter0_reg;
reg    ap_block_pp0_stage2_subdone_grp6_done_reg;
reg    ap_block_pp0_stage2_subdone_grp6;
reg    ap_condition_exit_pp0_iter0_stage2;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem_param_blk_n_AR;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_grp1;
reg    ap_block_pp0_stage1_subdone_grp1_done_reg;
reg    ap_block_pp0_stage1_subdone_grp1;
reg    ap_block_pp0_stage1_subdone;
reg    gmem_param_blk_n_R;
wire    ap_block_pp0_stage0_grp4;
reg    ap_block_pp0_stage0_subdone_grp4_done_reg;
reg    ap_block_pp0_stage0_subdone_grp4;
reg    ap_block_pp0_stage0_subdone;
wire    ap_block_pp0_stage2_grp2;
wire    ap_block_pp0_stage1_grp5;
reg    ap_block_pp0_stage1_subdone_grp5_done_reg;
reg    ap_block_pp0_stage1_subdone_grp5;
wire    ap_block_pp0_stage0_grp3;
reg    ap_block_pp0_stage0_subdone_grp3_done_reg;
reg    ap_block_pp0_stage0_subdone_grp3;
wire    ap_block_pp0_stage2_grp6;
wire  signed [59:0] sext_ln228_6_cast_fu_163_p1;
reg  signed [59:0] sext_ln228_6_cast_reg_259;
wire    ap_block_pp0_stage0_11001_grp0;
reg    ap_block_pp0_stage0_subdone_grp0_done_reg;
wire    ap_block_pp0_stage0_subdone_grp0;
wire  signed [59:0] sext_ln228_5_cast_fu_167_p1;
reg  signed [59:0] sext_ln228_5_cast_reg_264;
reg   [4:0] i_3_reg_269;
reg    ap_block_pp0_stage0_11001;
reg   [4:0] i_3_reg_269_pp0_iter1_reg;
reg   [4:0] i_3_reg_269_pp0_iter2_reg;
reg   [4:0] i_3_reg_269_pp0_iter3_reg;
wire   [0:0] icmp_ln228_fu_183_p2;
reg   [0:0] icmp_ln228_reg_274_pp0_iter1_reg;
reg   [0:0] icmp_ln228_reg_274_pp0_iter2_reg;
wire   [59:0] zext_ln228_3_fu_195_p1;
reg   [59:0] zext_ln228_3_reg_278;
wire   [59:0] add_ln230_fu_199_p2;
reg   [59:0] add_ln230_reg_284;
reg    ap_block_state2_io_grp1;
reg    ap_block_pp0_stage1_11001_grp1;
wire   [59:0] add_ln231_fu_220_p2;
reg   [59:0] add_ln231_reg_295;
wire    ap_block_pp0_stage1_11001_grp0;
reg    ap_block_pp0_stage1_subdone_grp0_done_reg;
wire    ap_block_pp0_stage1_subdone_grp0;
wire   [59:0] add_ln232_fu_224_p2;
reg   [59:0] add_ln232_reg_300;
reg    ap_block_pp0_stage2_11001_grp2;
reg    ap_block_pp0_stage0_11001_grp3;
reg   [255:0] gmem_param_addr_read_reg_317;
reg    ap_block_pp0_stage0_11001_grp4;
wire   [63:0] zext_ln228_fu_248_p1;
reg   [63:0] zext_ln228_reg_322;
reg   [255:0] gmem_param_addr_5_read_reg_328;
reg    ap_block_pp0_stage1_11001_grp5;
reg   [255:0] gmem_param_addr_6_read_reg_333;
reg    ap_block_pp0_stage2_11001_grp6;
wire    ap_block_pp0_stage1_grp0;
wire    ap_block_pp0_stage2_grp0;
wire    ap_block_pp0_stage0_grp0;
wire  signed [63:0] sext_ln230_fu_210_p1;
wire  signed [63:0] sext_ln231_fu_228_p1;
wire  signed [63:0] sext_ln232_fu_238_p1;
reg   [4:0] i_fu_66;
wire   [4:0] add_ln228_fu_189_p2;
wire    ap_loop_init;
reg   [4:0] ap_sig_allocacmp_i_3;
wire    ap_block_pp0_stage0;
reg    b_buf_we0_local;
reg    b_buf_ce0_local;
reg    g_buf_we0_local;
wire    ap_block_pp0_stage2_11001_grp0;
reg    ap_block_pp0_stage2_subdone_grp0_done_reg;
wire    ap_block_pp0_stage2_subdone_grp0;
reg    g_buf_ce0_local;
reg    be_buf_we0_local;
reg    be_buf_ce0_local;
wire  signed [59:0] sext_ln228_cast_fu_171_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_block_pp0_stage2_11001;
reg    ap_condition_exit_pp0_iter3_stage0;
reg    ap_idle_pp0_0to2;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [2:0] ap_NS_fsm;
reg    ap_idle_pp0_1to4;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_block_pp0_stage2_subdone_grp2_done_reg = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_block_pp0_stage2_subdone_grp6_done_reg = 1'b0;
#0 ap_block_pp0_stage1_subdone_grp1_done_reg = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp4_done_reg = 1'b0;
#0 ap_block_pp0_stage1_subdone_grp5_done_reg = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp3_done_reg = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp0_done_reg = 1'b0;
#0 ap_block_pp0_stage1_subdone_grp0_done_reg = 1'b0;
#0 i_fu_66 = 5'd0;
#0 ap_block_pp0_stage2_subdone_grp0_done_reg = 1'b0;
#0 ap_done_reg = 1'b0;
end

upconv_core_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage2),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
                ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp0)) begin
                ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp3_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
                ap_block_pp0_stage0_subdone_grp3_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp3)) begin
                ap_block_pp0_stage0_subdone_grp3_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp4_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
                ap_block_pp0_stage0_subdone_grp4_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp4)) begin
                ap_block_pp0_stage0_subdone_grp4_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage1_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage1)) begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_block_pp0_stage1_subdone_grp0_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone_grp0)) begin
                ap_block_pp0_stage1_subdone_grp0_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage1_subdone_grp1_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage1)) begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_block_pp0_stage1_subdone_grp1_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone_grp1)) begin
                ap_block_pp0_stage1_subdone_grp1_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage1_subdone_grp5_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage1)) begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_block_pp0_stage1_subdone_grp5_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone_grp5)) begin
                ap_block_pp0_stage1_subdone_grp5_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage2_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage2)) begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_block_pp0_stage2_subdone_grp0_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage2_subdone_grp0)) begin
                ap_block_pp0_stage2_subdone_grp0_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage2_subdone_grp2_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage2)) begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_block_pp0_stage2_subdone_grp2_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage2_subdone_grp2)) begin
                ap_block_pp0_stage2_subdone_grp2_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage2_subdone_grp6_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage2)) begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_block_pp0_stage2_subdone_grp6_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage2_subdone_grp6)) begin
                ap_block_pp0_stage2_subdone_grp6_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage2)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter4 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to2 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter3_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to2 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter3_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to2 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter3_stage0))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((icmp_ln228_fu_183_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_66 <= add_ln228_fu_189_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_66 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        add_ln230_reg_284 <= add_ln230_fu_199_p2;
        i_3_reg_269 <= ap_sig_allocacmp_i_3;
        i_3_reg_269_pp0_iter1_reg <= i_3_reg_269;
        i_3_reg_269_pp0_iter2_reg <= i_3_reg_269_pp0_iter1_reg;
        i_3_reg_269_pp0_iter3_reg <= i_3_reg_269_pp0_iter2_reg;
        icmp_ln228_reg_274 <= icmp_ln228_fu_183_p2;
        icmp_ln228_reg_274_pp0_iter1_reg <= icmp_ln228_reg_274;
        icmp_ln228_reg_274_pp0_iter2_reg <= icmp_ln228_reg_274_pp0_iter1_reg;
        zext_ln228_3_reg_278[4 : 0] <= zext_ln228_3_fu_195_p1[4 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0))) begin
        add_ln231_reg_295 <= add_ln231_fu_220_p2;
        add_ln232_reg_300 <= add_ln232_fu_224_p2;
        zext_ln228_reg_322[4 : 0] <= zext_ln228_fu_248_p1[4 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001_grp5) & (1'b0 == ap_block_pp0_stage1_subdone_grp5_done_reg))) begin
        gmem_param_addr_5_read_reg_328 <= m_axi_gmem_param_0_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001_grp6) & (1'b0 == ap_block_pp0_stage2_subdone_grp6_done_reg))) begin
        gmem_param_addr_6_read_reg_333 <= m_axi_gmem_param_0_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp4) & (1'b0 == ap_block_pp0_stage0_subdone_grp4_done_reg))) begin
        gmem_param_addr_read_reg_317 <= m_axi_gmem_param_0_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sext_ln228_5_cast_reg_264 <= sext_ln228_5_cast_fu_167_p1;
        sext_ln228_6_cast_reg_259 <= sext_ln228_6_cast_fu_163_p1;
    end
end

always @ (*) begin
    if (((icmp_ln228_reg_274 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
        ap_condition_exit_pp0_iter0_stage2 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage2 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln228_reg_274_pp0_iter2_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter3_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter3_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to2 = 1'b1;
    end else begin
        ap_idle_pp0_0to2 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to4 = 1'b1;
    end else begin
        ap_idle_pp0_1to4 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_i_3 = 5'd0;
    end else begin
        ap_sig_allocacmp_i_3 = i_fu_66;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0))) begin
        b_buf_ce0_local = 1'b1;
    end else begin
        b_buf_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0))) begin
        b_buf_we0_local = 1'b1;
    end else begin
        b_buf_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        be_buf_ce0_local = 1'b1;
    end else begin
        be_buf_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        be_buf_we0_local = 1'b1;
    end else begin
        be_buf_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage2_11001_grp0))) begin
        g_buf_ce0_local = 1'b1;
    end else begin
        g_buf_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage2_11001_grp0))) begin
        g_buf_we0_local = 1'b1;
    end else begin
        g_buf_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp3_done_reg) & (1'b0 == ap_block_pp0_stage0_grp3)) | ((icmp_ln228_reg_274 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_grp2) & (1'b0 == ap_block_pp0_stage2_subdone_grp2_done_reg)) | ((icmp_ln228_reg_274 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp1_done_reg) & (1'b0 == ap_block_pp0_stage1_grp1)))) begin
        gmem_param_blk_n_AR = m_axi_gmem_param_0_ARREADY;
    end else begin
        gmem_param_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_grp6) & (1'b0 == ap_block_pp0_stage2_subdone_grp6_done_reg)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp4_done_reg) & (1'b0 == ap_block_pp0_stage0_grp4)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone_grp5_done_reg) & (1'b0 == ap_block_pp0_stage1_grp5)))) begin
        gmem_param_blk_n_R = m_axi_gmem_param_0_RVALID;
    end else begin
        gmem_param_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp3) & (1'b0 == ap_block_pp0_stage0_subdone_grp3_done_reg))) begin
        m_axi_gmem_param_0_ARADDR = sext_ln232_fu_238_p1;
    end else if (((icmp_ln228_reg_274 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001_grp2) & (1'b0 == ap_block_pp0_stage2_subdone_grp2_done_reg))) begin
        m_axi_gmem_param_0_ARADDR = sext_ln231_fu_228_p1;
    end else if (((icmp_ln228_reg_274 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001_grp1) & (1'b0 == ap_block_pp0_stage1_subdone_grp1_done_reg))) begin
        m_axi_gmem_param_0_ARADDR = sext_ln230_fu_210_p1;
    end else begin
        m_axi_gmem_param_0_ARADDR = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp3) & (1'b0 == ap_block_pp0_stage0_subdone_grp3_done_reg)) | ((icmp_ln228_reg_274 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001_grp2) & (1'b0 == ap_block_pp0_stage2_subdone_grp2_done_reg)) | ((icmp_ln228_reg_274 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001_grp1) & (1'b0 == ap_block_pp0_stage1_subdone_grp1_done_reg)))) begin
        m_axi_gmem_param_0_ARVALID = 1'b1;
    end else begin
        m_axi_gmem_param_0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001_grp6) & (1'b0 == ap_block_pp0_stage2_subdone_grp6_done_reg)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp4) & (1'b0 == ap_block_pp0_stage0_subdone_grp4_done_reg)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001_grp5) & (1'b0 == ap_block_pp0_stage1_subdone_grp5_done_reg)))) begin
        m_axi_gmem_param_0_RREADY = 1'b1;
    end else begin
        m_axi_gmem_param_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if (((ap_idle_pp0_0to2 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter3_stage0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to4 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln228_fu_189_p2 = (ap_sig_allocacmp_i_3 + 5'd1);

assign add_ln230_fu_199_p2 = ($signed(zext_ln228_3_fu_195_p1) + $signed(sext_ln228_cast_fu_171_p1));

assign add_ln231_fu_220_p2 = ($signed(zext_ln228_3_reg_278) + $signed(sext_ln228_5_cast_reg_264));

assign add_ln232_fu_224_p2 = ($signed(zext_ln228_3_reg_278) + $signed(sext_ln228_6_cast_reg_259));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((m_axi_gmem_param_0_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp3_done_reg)) | ((m_axi_gmem_param_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp4_done_reg)));
end

assign ap_block_pp0_stage0_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001_grp3 = ((m_axi_gmem_param_0_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp3_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp4 = ((m_axi_gmem_param_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp4_done_reg));
end

assign ap_block_pp0_stage0_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp3 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp4 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((m_axi_gmem_param_0_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp3_done_reg)) | ((m_axi_gmem_param_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp4_done_reg)));
end

assign ap_block_pp0_stage0_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone_grp3 = ((m_axi_gmem_param_0_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp3_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone_grp4 = ((m_axi_gmem_param_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp4_done_reg));
end

assign ap_block_pp0_stage1_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_11001_grp1 = ((1'b1 == ap_block_state2_io_grp1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp1_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage1_11001_grp5 = ((m_axi_gmem_param_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp5_done_reg));
end

assign ap_block_pp0_stage1_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_grp1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_grp5 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_subdone = (((1'b1 == ap_block_state2_io_grp1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp1_done_reg)) | ((m_axi_gmem_param_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp5_done_reg)));
end

assign ap_block_pp0_stage1_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_subdone_grp1 = ((1'b1 == ap_block_state2_io_grp1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp1_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage1_subdone_grp5 = ((m_axi_gmem_param_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp5_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage2_11001 = (((m_axi_gmem_param_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone_grp6_done_reg)) | ((1'b1 == ap_block_state3_io_grp2) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone_grp2_done_reg)));
end

assign ap_block_pp0_stage2_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_11001_grp2 = ((1'b1 == ap_block_state3_io_grp2) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone_grp2_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage2_11001_grp6 = ((m_axi_gmem_param_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone_grp6_done_reg));
end

assign ap_block_pp0_stage2_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_grp2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_grp6 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_subdone = (((m_axi_gmem_param_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone_grp6_done_reg)) | ((1'b1 == ap_block_state3_io_grp2) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone_grp2_done_reg)));
end

assign ap_block_pp0_stage2_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_subdone_grp2 = ((1'b1 == ap_block_state3_io_grp2) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone_grp2_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage2_subdone_grp6 = ((m_axi_gmem_param_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone_grp6_done_reg));
end

always @ (*) begin
    ap_block_state2_io_grp1 = ((icmp_ln228_reg_274 == 1'd0) & (m_axi_gmem_param_0_ARREADY == 1'b0));
end

always @ (*) begin
    ap_block_state3_io_grp2 = ((icmp_ln228_reg_274 == 1'd0) & (m_axi_gmem_param_0_ARREADY == 1'b0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage2;

assign ap_ready = ap_ready_sig;

assign b_buf_address0 = zext_ln228_fu_248_p1;

assign b_buf_ce0 = b_buf_ce0_local;

assign b_buf_d0 = gmem_param_addr_read_reg_317;

assign b_buf_we0 = b_buf_we0_local;

assign be_buf_address0 = zext_ln228_reg_322;

assign be_buf_ce0 = be_buf_ce0_local;

assign be_buf_d0 = gmem_param_addr_6_read_reg_333;

assign be_buf_we0 = be_buf_we0_local;

assign g_buf_address0 = zext_ln228_reg_322;

assign g_buf_ce0 = g_buf_ce0_local;

assign g_buf_d0 = gmem_param_addr_5_read_reg_328;

assign g_buf_we0 = g_buf_we0_local;

assign icmp_ln228_fu_183_p2 = ((ap_sig_allocacmp_i_3 == 5'd30) ? 1'b1 : 1'b0);

assign m_axi_gmem_param_0_ARBURST = 2'd0;

assign m_axi_gmem_param_0_ARCACHE = 4'd0;

assign m_axi_gmem_param_0_ARID = 1'd0;

assign m_axi_gmem_param_0_ARLEN = 64'd1;

assign m_axi_gmem_param_0_ARLOCK = 2'd0;

assign m_axi_gmem_param_0_ARPROT = 3'd0;

assign m_axi_gmem_param_0_ARQOS = 4'd0;

assign m_axi_gmem_param_0_ARREGION = 4'd0;

assign m_axi_gmem_param_0_ARSIZE = 3'd0;

assign m_axi_gmem_param_0_ARUSER = 1'd0;

assign m_axi_gmem_param_0_AWADDR = 64'd0;

assign m_axi_gmem_param_0_AWBURST = 2'd0;

assign m_axi_gmem_param_0_AWCACHE = 4'd0;

assign m_axi_gmem_param_0_AWID = 1'd0;

assign m_axi_gmem_param_0_AWLEN = 32'd0;

assign m_axi_gmem_param_0_AWLOCK = 2'd0;

assign m_axi_gmem_param_0_AWPROT = 3'd0;

assign m_axi_gmem_param_0_AWQOS = 4'd0;

assign m_axi_gmem_param_0_AWREGION = 4'd0;

assign m_axi_gmem_param_0_AWSIZE = 3'd0;

assign m_axi_gmem_param_0_AWUSER = 1'd0;

assign m_axi_gmem_param_0_AWVALID = 1'b0;

assign m_axi_gmem_param_0_BREADY = 1'b0;

assign m_axi_gmem_param_0_WDATA = 256'd0;

assign m_axi_gmem_param_0_WID = 1'd0;

assign m_axi_gmem_param_0_WLAST = 1'b0;

assign m_axi_gmem_param_0_WSTRB = 32'd0;

assign m_axi_gmem_param_0_WUSER = 1'd0;

assign m_axi_gmem_param_0_WVALID = 1'b0;

assign sext_ln228_5_cast_fu_167_p1 = $signed(sext_ln228_5);

assign sext_ln228_6_cast_fu_163_p1 = $signed(sext_ln228_6);

assign sext_ln228_cast_fu_171_p1 = $signed(sext_ln228);

assign sext_ln230_fu_210_p1 = $signed(add_ln230_reg_284);

assign sext_ln231_fu_228_p1 = $signed(add_ln231_reg_295);

assign sext_ln232_fu_238_p1 = $signed(add_ln232_reg_300);

assign zext_ln228_3_fu_195_p1 = ap_sig_allocacmp_i_3;

assign zext_ln228_fu_248_p1 = i_3_reg_269_pp0_iter3_reg;

always @ (posedge ap_clk) begin
    zext_ln228_3_reg_278[59:5] <= 55'b0000000000000000000000000000000000000000000000000000000;
    zext_ln228_reg_322[63:5] <= 59'b00000000000000000000000000000000000000000000000000000000000;
end

endmodule //upconv_core_top_UpConv_Fused_Row_8_16_16_960_480_Pipeline_LOAD_PARAMS
