// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module upconv_core_top_upconv_core_top_Pipeline_LOAD_ROW (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem_in_0_AWVALID,
        m_axi_gmem_in_0_AWREADY,
        m_axi_gmem_in_0_AWADDR,
        m_axi_gmem_in_0_AWID,
        m_axi_gmem_in_0_AWLEN,
        m_axi_gmem_in_0_AWSIZE,
        m_axi_gmem_in_0_AWBURST,
        m_axi_gmem_in_0_AWLOCK,
        m_axi_gmem_in_0_AWCACHE,
        m_axi_gmem_in_0_AWPROT,
        m_axi_gmem_in_0_AWQOS,
        m_axi_gmem_in_0_AWREGION,
        m_axi_gmem_in_0_AWUSER,
        m_axi_gmem_in_0_WVALID,
        m_axi_gmem_in_0_WREADY,
        m_axi_gmem_in_0_WDATA,
        m_axi_gmem_in_0_WSTRB,
        m_axi_gmem_in_0_WLAST,
        m_axi_gmem_in_0_WID,
        m_axi_gmem_in_0_WUSER,
        m_axi_gmem_in_0_ARVALID,
        m_axi_gmem_in_0_ARREADY,
        m_axi_gmem_in_0_ARADDR,
        m_axi_gmem_in_0_ARID,
        m_axi_gmem_in_0_ARLEN,
        m_axi_gmem_in_0_ARSIZE,
        m_axi_gmem_in_0_ARBURST,
        m_axi_gmem_in_0_ARLOCK,
        m_axi_gmem_in_0_ARCACHE,
        m_axi_gmem_in_0_ARPROT,
        m_axi_gmem_in_0_ARQOS,
        m_axi_gmem_in_0_ARREGION,
        m_axi_gmem_in_0_ARUSER,
        m_axi_gmem_in_0_RVALID,
        m_axi_gmem_in_0_RREADY,
        m_axi_gmem_in_0_RDATA,
        m_axi_gmem_in_0_RLAST,
        m_axi_gmem_in_0_RID,
        m_axi_gmem_in_0_RFIFONUM,
        m_axi_gmem_in_0_RUSER,
        m_axi_gmem_in_0_RRESP,
        m_axi_gmem_in_0_BVALID,
        m_axi_gmem_in_0_BREADY,
        m_axi_gmem_in_0_BRESP,
        m_axi_gmem_in_0_BID,
        m_axi_gmem_in_0_BUSER,
        empty,
        shl_ln1,
        base_buf,
        sext_ln397,
        x_buf_address0,
        x_buf_ce0,
        x_buf_we0,
        x_buf_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem_in_0_AWVALID;
input   m_axi_gmem_in_0_AWREADY;
output  [63:0] m_axi_gmem_in_0_AWADDR;
output  [0:0] m_axi_gmem_in_0_AWID;
output  [31:0] m_axi_gmem_in_0_AWLEN;
output  [2:0] m_axi_gmem_in_0_AWSIZE;
output  [1:0] m_axi_gmem_in_0_AWBURST;
output  [1:0] m_axi_gmem_in_0_AWLOCK;
output  [3:0] m_axi_gmem_in_0_AWCACHE;
output  [2:0] m_axi_gmem_in_0_AWPROT;
output  [3:0] m_axi_gmem_in_0_AWQOS;
output  [3:0] m_axi_gmem_in_0_AWREGION;
output  [0:0] m_axi_gmem_in_0_AWUSER;
output   m_axi_gmem_in_0_WVALID;
input   m_axi_gmem_in_0_WREADY;
output  [255:0] m_axi_gmem_in_0_WDATA;
output  [31:0] m_axi_gmem_in_0_WSTRB;
output   m_axi_gmem_in_0_WLAST;
output  [0:0] m_axi_gmem_in_0_WID;
output  [0:0] m_axi_gmem_in_0_WUSER;
output   m_axi_gmem_in_0_ARVALID;
input   m_axi_gmem_in_0_ARREADY;
output  [63:0] m_axi_gmem_in_0_ARADDR;
output  [0:0] m_axi_gmem_in_0_ARID;
output  [31:0] m_axi_gmem_in_0_ARLEN;
output  [2:0] m_axi_gmem_in_0_ARSIZE;
output  [1:0] m_axi_gmem_in_0_ARBURST;
output  [1:0] m_axi_gmem_in_0_ARLOCK;
output  [3:0] m_axi_gmem_in_0_ARCACHE;
output  [2:0] m_axi_gmem_in_0_ARPROT;
output  [3:0] m_axi_gmem_in_0_ARQOS;
output  [3:0] m_axi_gmem_in_0_ARREGION;
output  [0:0] m_axi_gmem_in_0_ARUSER;
input   m_axi_gmem_in_0_RVALID;
output   m_axi_gmem_in_0_RREADY;
input  [255:0] m_axi_gmem_in_0_RDATA;
input   m_axi_gmem_in_0_RLAST;
input  [0:0] m_axi_gmem_in_0_RID;
input  [10:0] m_axi_gmem_in_0_RFIFONUM;
input  [0:0] m_axi_gmem_in_0_RUSER;
input  [1:0] m_axi_gmem_in_0_RRESP;
input   m_axi_gmem_in_0_BVALID;
output   m_axi_gmem_in_0_BREADY;
input  [1:0] m_axi_gmem_in_0_BRESP;
input  [0:0] m_axi_gmem_in_0_BID;
input  [0:0] m_axi_gmem_in_0_BUSER;
input  [12:0] empty;
input  [24:0] shl_ln1;
input  [10:0] base_buf;
input  [58:0] sext_ln397;
output  [10:0] x_buf_address0;
output   x_buf_ce0;
output   x_buf_we0;
output  [255:0] x_buf_d0;

reg ap_idle;
reg m_axi_gmem_in_0_ARVALID;
reg m_axi_gmem_in_0_RREADY;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_idle_pp0;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln400_fu_155_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem_in_blk_n_AR;
wire    ap_block_pp0_stage0_grp1;
reg    gmem_in_blk_n_R;
wire    ap_block_pp0_stage0_11001_grp0;
reg    ap_block_pp0_stage0_subdone_grp0_done_reg;
wire    ap_block_pp0_stage0_subdone_grp0;
reg    ap_block_pp0_stage0_11001_grp1;
wire  signed [59:0] sext_ln397_cast_fu_139_p1;
reg  signed [59:0] sext_ln397_cast_reg_246;
reg   [11:0] m_reg_251;
reg    ap_block_pp0_stage0_11001;
wire   [10:0] add_ln403_1_fu_205_p2;
reg   [10:0] add_ln403_1_reg_261;
reg   [10:0] add_ln403_1_reg_261_pp0_iter2_reg;
reg   [10:0] add_ln403_1_reg_261_pp0_iter3_reg;
reg   [10:0] add_ln403_1_reg_261_pp0_iter4_reg;
reg   [10:0] add_ln403_1_reg_261_pp0_iter5_reg;
reg   [10:0] add_ln403_1_reg_261_pp0_iter6_reg;
reg   [10:0] add_ln403_1_reg_261_pp0_iter7_reg;
reg   [10:0] add_ln403_1_reg_261_pp0_iter8_reg;
reg   [10:0] add_ln403_1_reg_261_pp0_iter9_reg;
reg   [10:0] add_ln403_1_reg_261_pp0_iter10_reg;
wire   [59:0] add_ln403_2_fu_210_p2;
reg   [59:0] add_ln403_2_reg_266;
reg   [255:0] gmem_in_addr_read_reg_277;
wire   [63:0] zext_ln403_2_fu_225_p1;
wire    ap_block_pp0_stage0_grp0;
wire  signed [63:0] sext_ln403_fu_215_p1;
reg   [11:0] m_1_fu_86;
wire   [11:0] add_ln400_fu_161_p2;
wire    ap_loop_init;
reg   [11:0] ap_sig_allocacmp_m;
wire    ap_block_pp0_stage0;
reg    x_buf_we0_local;
reg    x_buf_ce0_local;
wire   [12:0] zext_ln400_fu_151_p1;
wire   [16:0] shl_ln4_fu_175_p3;
wire   [24:0] zext_ln403_fu_182_p1;
wire   [24:0] add_ln403_fu_186_p2;
wire   [19:0] lshr_ln_fu_191_p4;
wire   [10:0] trunc_ln400_fu_172_p1;
wire   [59:0] zext_ln403_1_fu_201_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp0_done_reg = 1'b0;
#0 m_1_fu_86 = 12'd0;
#0 ap_done_reg = 1'b0;
end

upconv_core_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp0)) begin
            ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter10_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln400_fu_155_p2 == 1'd0))) begin
            m_1_fu_86 <= add_ln400_fu_161_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            m_1_fu_86 <= 12'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        add_ln403_1_reg_261 <= add_ln403_1_fu_205_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        add_ln403_1_reg_261_pp0_iter10_reg <= add_ln403_1_reg_261_pp0_iter9_reg;
        add_ln403_1_reg_261_pp0_iter2_reg <= add_ln403_1_reg_261;
        add_ln403_1_reg_261_pp0_iter3_reg <= add_ln403_1_reg_261_pp0_iter2_reg;
        add_ln403_1_reg_261_pp0_iter4_reg <= add_ln403_1_reg_261_pp0_iter3_reg;
        add_ln403_1_reg_261_pp0_iter5_reg <= add_ln403_1_reg_261_pp0_iter4_reg;
        add_ln403_1_reg_261_pp0_iter6_reg <= add_ln403_1_reg_261_pp0_iter5_reg;
        add_ln403_1_reg_261_pp0_iter7_reg <= add_ln403_1_reg_261_pp0_iter6_reg;
        add_ln403_1_reg_261_pp0_iter8_reg <= add_ln403_1_reg_261_pp0_iter7_reg;
        add_ln403_1_reg_261_pp0_iter9_reg <= add_ln403_1_reg_261_pp0_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        add_ln403_2_reg_266 <= add_ln403_2_fu_210_p2;
        sext_ln397_cast_reg_246 <= sext_ln397_cast_fu_139_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        m_reg_251 <= ap_sig_allocacmp_m;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        gmem_in_addr_read_reg_277 <= m_axi_gmem_in_0_RDATA;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln400_fu_155_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter10_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_m = 12'd0;
    end else begin
        ap_sig_allocacmp_m = m_1_fu_86;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_grp1))) begin
        gmem_in_blk_n_AR = m_axi_gmem_in_0_ARREADY;
    end else begin
        gmem_in_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_grp1))) begin
        gmem_in_blk_n_R = m_axi_gmem_in_0_RVALID;
    end else begin
        gmem_in_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        m_axi_gmem_in_0_ARVALID = 1'b1;
    end else begin
        m_axi_gmem_in_0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        m_axi_gmem_in_0_RREADY = 1'b1;
    end else begin
        m_axi_gmem_in_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        x_buf_ce0_local = 1'b1;
    end else begin
        x_buf_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        x_buf_we0_local = 1'b1;
    end else begin
        x_buf_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln400_fu_161_p2 = (ap_sig_allocacmp_m + 12'd1);

assign add_ln403_1_fu_205_p2 = (trunc_ln400_fu_172_p1 + base_buf);

assign add_ln403_2_fu_210_p2 = ($signed(zext_ln403_1_fu_201_p1) + $signed(sext_ln397_cast_reg_246));

assign add_ln403_fu_186_p2 = (shl_ln1 + zext_ln403_fu_182_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((m_axi_gmem_in_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b1)) | ((m_axi_gmem_in_0_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)));
end

assign ap_block_pp0_stage0_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = (((m_axi_gmem_in_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b1)) | ((m_axi_gmem_in_0_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)));
end

assign ap_block_pp0_stage0_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((m_axi_gmem_in_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b1)) | ((m_axi_gmem_in_0_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)));
end

assign ap_block_pp0_stage0_subdone_grp0 = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln400_fu_155_p2 = ((zext_ln400_fu_151_p1 == empty) ? 1'b1 : 1'b0);

assign lshr_ln_fu_191_p4 = {{add_ln403_fu_186_p2[24:5]}};

assign m_axi_gmem_in_0_ARADDR = sext_ln403_fu_215_p1;

assign m_axi_gmem_in_0_ARBURST = 2'd0;

assign m_axi_gmem_in_0_ARCACHE = 4'd0;

assign m_axi_gmem_in_0_ARID = 1'd0;

assign m_axi_gmem_in_0_ARLEN = 64'd1;

assign m_axi_gmem_in_0_ARLOCK = 2'd0;

assign m_axi_gmem_in_0_ARPROT = 3'd0;

assign m_axi_gmem_in_0_ARQOS = 4'd0;

assign m_axi_gmem_in_0_ARREGION = 4'd0;

assign m_axi_gmem_in_0_ARSIZE = 3'd0;

assign m_axi_gmem_in_0_ARUSER = 1'd0;

assign m_axi_gmem_in_0_AWADDR = 64'd0;

assign m_axi_gmem_in_0_AWBURST = 2'd0;

assign m_axi_gmem_in_0_AWCACHE = 4'd0;

assign m_axi_gmem_in_0_AWID = 1'd0;

assign m_axi_gmem_in_0_AWLEN = 32'd0;

assign m_axi_gmem_in_0_AWLOCK = 2'd0;

assign m_axi_gmem_in_0_AWPROT = 3'd0;

assign m_axi_gmem_in_0_AWQOS = 4'd0;

assign m_axi_gmem_in_0_AWREGION = 4'd0;

assign m_axi_gmem_in_0_AWSIZE = 3'd0;

assign m_axi_gmem_in_0_AWUSER = 1'd0;

assign m_axi_gmem_in_0_AWVALID = 1'b0;

assign m_axi_gmem_in_0_BREADY = 1'b0;

assign m_axi_gmem_in_0_WDATA = 256'd0;

assign m_axi_gmem_in_0_WID = 1'd0;

assign m_axi_gmem_in_0_WLAST = 1'b0;

assign m_axi_gmem_in_0_WSTRB = 32'd0;

assign m_axi_gmem_in_0_WUSER = 1'd0;

assign m_axi_gmem_in_0_WVALID = 1'b0;

assign sext_ln397_cast_fu_139_p1 = $signed(sext_ln397);

assign sext_ln403_fu_215_p1 = $signed(add_ln403_2_reg_266);

assign shl_ln4_fu_175_p3 = {{m_reg_251}, {5'd0}};

assign trunc_ln400_fu_172_p1 = m_reg_251[10:0];

assign x_buf_address0 = zext_ln403_2_fu_225_p1;

assign x_buf_ce0 = x_buf_ce0_local;

assign x_buf_d0 = gmem_in_addr_read_reg_277;

assign x_buf_we0 = x_buf_we0_local;

assign zext_ln400_fu_151_p1 = ap_sig_allocacmp_m;

assign zext_ln403_1_fu_201_p1 = lshr_ln_fu_191_p4;

assign zext_ln403_2_fu_225_p1 = add_ln403_1_reg_261_pp0_iter10_reg;

assign zext_ln403_fu_182_p1 = shl_ln4_fu_175_p3;

endmodule //upconv_core_top_upconv_core_top_Pipeline_LOAD_ROW
